<?php
/**
 * @file
 * Code for the nm_administration feature.
 */

include_once 'nm_administration.features.inc';


/**
 * @param $variables
 */
function nm_administration_preprocess_panels_pane(&$variables) {
  if (arg(0) == "administration") {
    drupal_add_css(drupal_get_path('module', 'nm_administration') . "/css/nm_administration.css");
    drupal_add_js(drupal_get_path('module', 'nm_administration') . "/js/nm_administration.js");
  }

}


/**
 *
 */
function nm_administration_add_user_form() {
  $form = drupal_get_form('user_register_form');

  return $form;
}


/**
 * @return string
 */
function nm_administration_render_add_user_form() {
  $user_add_form = drupal_get_form("nm_administration_add_user_form");
  $create_fieldset = [];
  $create_fieldset['create_new'] = [
    '#type' => 'fieldset',
    '#title' => t('Add user'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    'content' => [
      '#type' => 'markup',
      '#markup' => drupal_render($user_add_form),
    ],
  ];

  return drupal_render($create_fieldset);
}

