<?php

/**
 * @file
 * sidebar fuer den h5p-player
 */
/**
 * @ingroup image
 * @{
 */

/**
 * Implements hook_init().
 */
function h5p_annotationlist_init() {

  //17.10.2015 - 00:06 - SN
  //todo - include if necessarry only. e.g. page_view callback
  //node prepare view or something

  $nid = (arg(0) == 'node' && is_numeric(arg(1))) ? arg(1) : NULL;

  drupal_add_js(array('h5psidebar' => array('json_video_id' => 'cid-' . $nid)), 'setting');
  drupal_add_js(drupal_get_path('module', 'h5p_annotationlist') . '/assets/javascript/sprintf.js');
  drupal_add_js(drupal_get_path('module', 'h5p_annotationlist') . '/assets/javascript/h5p_annotationlist.js');

  drupal_add_css(drupal_get_path('module', 'h5p_annotationlist') . '/assets/css/h5p_annotationlist.css',  array('group' => CSS_DEFAULT, 'every_page' => TRUE));
  drupal_add_css(drupal_get_path('module', 'h5p_annotationlist') . '/assets/css/font-awesome.min.css',  array('group' => CSS_DEFAULT, 'every_page' => TRUE));
 
}

/**
 * @} End of "ingroup image".
 */
