<?php


/**
 * Implements hook_form_alter().
 * Temporär Fehlermeldung, da h5p-library einen Bug hat
 */
function h5p_integration_form_alter(&$form, &$form_state, $form_id) {

    if ($form_id == 'h5p_content_node_form') {
        drupal_add_js(drupal_get_path('module', 'h5p_integration') . "/common_js/leave_h5p_warning.js");
    }
}

/**
 * Implements hook_wysiwyg_plugin
 * @param type $editor
 * @param type $version
 * @return type
 */
function h5p_integration_wysiwyg_plugin($editor, $version) {
#return false;
  //do not show H5P Plugin in Projects section
  if(section_projects_get_active_project()){
    return;
  }

  //_linkit_add_settings($editor);
  switch ($editor) {
    case 'ckeditor':
      /*wichtiger hinweis. beim entwickeln solcher plugins sind IDs extrem wichtig!
       Also Buttons in PHP und JS gleich benennen und auch der Modulname (hier der array-key)
       sollte wieder auftauchen.
       Ansonsten kommt es zu einem strangen is null js fehler*/
      return array(
        'h5p_integration' => array(
          'path' => drupal_get_path('module', 'h5p_integration') . '/wysiwyg_plugin',
          'buttons' => array(
            'h5p_button' => t('H5P Interactive Content'),
          ),
          'load' => TRUE,
        ),
      );
  }
}
 
/**
 *  FILTER
 */

/**
 * Implements hook_filter_info().
 *
 */
function h5p_integration_filter_info() {
  $filters['filter_content_h5p'] = array(
    'title' => t('Content - H5 Filter'),
    'description' => t('Every [h5p](node_id)[/h5p] pattern is being replaced by its content.'),
    'process callback' => '_h5p_integration_filter_h5p_process',
    'tips callback' => '_h5p_integration_filter_h5p_tips',
    'cache' => FALSE,
  );
  return $filters;
}

/**
 * Content - h5p Filter  process callback.
 *
 * The actual filtering is performed here. The supplied text should be returned,
 * once any necessary substitutions have taken place. The example just replaces
 * foo with our custom defined string in the settings page.
 */
function _h5p_integration_filter_h5p_process($text, $filter, $format) {
  //$replacement = isset($filter->settings['filter_example_foo']) ? $filter->settings['filter_example_foo'] : 'bar';
  //return str_replace('foo', $replacement, $text);
  $regex = '#\[h5p\]([0-9]+)(:*.*?)\[\/h5p\]#s';

  return preg_replace_callback($regex, '_h5p_integration_h5p_replacements', $text);
}

function _h5p_integration_h5p_replacements($matches) {
  //preg_match($regex, $text, $matches);
  //$match = $matches[0];
  $text = "";

  if (!empty($matches) && count($matches) > 1) {

    $nid = $matches[1];
    $node = node_load($nid);

    if ($node != FALSE && node_access('view', $node) && $node->status) {

      //bei embed auch den view-mode anpassen
      $node_view = node_view($node, 'embed', NULL);

      //28.05.2013 - 12:22 - SN hack, title must be unset at another place (template)
      if (isset($node_view['#node']->title)) {
        $node_view['#node']->title = "";
      }
      //dpm($node_view);
      $node_output = drupal_render($node_view);
      //$text = preg_replace($regex, $node_output, $text);
      $text = '<div class="embeded_h5p">' . $node_output . '</div>';
    }
  }

  return $text;
}

/**
 * shows a warning to dozent / autor if inserted h5p-node is not visible for students
 * @param StdClass $h5p_node_object a h5p-node
 * @param StdClass $contend_node where the h5p is used, eg  lehrtext-kapitel
 */
function _h5p_integration_show_warning_if_h5p_not_accessible($h5p_node_object, $content_node) {
    //aktuell besuchter lehrtext: entweder group ref oder book-bid (bei der ersten seite v.a.)
    $current_domain_nid = @$content_node->og_group_ref[LANGUAGE_NONE][0]['target_id']? : @$content_node->book['bid'];
    $h5p_domain_nid = @$h5p_node_object->og_group_ref[LANGUAGE_NONE][0]['target_id'];

    //falls kontext einer group / lehrtext angehört und h5p einer group angehört
    if ($current_domain_nid && $h5p_domain_nid) {
        //check if h5p content is visible in active domain
        if (!og_is_member('node', $current_domain_nid, 'node', $h5p_node_object)) {
            //check if user may edit h5p and domain content node
            if (node_access('update', $h5p_node_object) && node_access('update', $content_node)) {
                drupal_set_message("Es wurde ein H5P Inhalt eingebettet, der nicht für dieses Thema freigeschaltet ist. " . l("Bitte schalten Sie diesen Inhalt hier frei.", 'domain/edit/' . $h5p_node_object->nid), 'warning');
            }
            //zeige warning nur fuer bearbeiter des contents. Normalen Nutzern bringt das nichts. 
            elseif (node_access('update', $content_node)) {
                drupal_set_message("Es wurde ein H5P Inhalt eingebettet, der nicht für dieses Thema freigeschaltet ist! Dieser ist für Kursteilnehmer nicht sichtbar. ", 'error');
            }
        }
    }
}

/**
 * hook_node_view um bei eingebetteten  h5p-elementen  eine warning einzublenden
 * @param type $node
 * @param type $view_mode
 * @param type $langcode
 */
function h5p_integration_node_view($node, $view_mode, $langcode) {

  $page_node = menu_get_object();
  if(empty($page_node))
    
      $page_node = node_load(arg(2)); 
  
  if (!empty($page_node) && $node->type == NM_INTERACTIVE_CONTENT &&  $node->nid != $page_node->nid) {
      _h5p_integration_show_warning_if_h5p_not_accessible($node, $page_node);
  }
}

/**
 * Filter tips callback for foo filter.
 *
 * The tips callback allows filters to provide help text to users during the
 * content editing process. Short tips are provided on the content editing
 * screen, while long tips are provided on a separate linked page. Short tips
 * are optional, but long tips are highly recommended.
 */
function _h5p_integration_filter_h5p_tips($filter, $format, $long = FALSE) {

  return t('Every [h5p](node_id)[/h5p] pattern is being replaced by its content.');
}
