<?php

//Semester Logic
//year when the vhb ID started - needed for calculation
define("NM_VHB_SEMESTERID_START_YEAR", '84');
//vhb semester id when the first onlinekurslabor course was online
define("NM_VHB_SEMESTERID_OKL_START", '58');
//semester when okl started (WS 13/14)
define("NM_VHB_SEMESTERID_OKL_START_DATE", '10.2013');

//System
define("NM_FILTER_FORMAT_FILTERED_HTML", 'filtered_html');

//Blocks
define("NM_BLOCK_AUTOREN", 53);

//Content
define("NM_DOMAIN_OVERVIEW_ID", 7); //deprecated
define("NM_DOMAIN_OVERVIEW_PATH", "domains");
define("NM_MEDIA_PATH", "domain/media");
define("NM_BIBLIO_PATH", "domain/biblio");
define("NM_TASKS_PATH", "domain/tasks");
define("NM_CONTENT_DOMAIN_PATH", "domain");
define("NM_CONTENT_TEXT_PATH", "domain/text");
define("NM_CONTENT_ADD_CONTENT_PATH", "domain/add");
define("NM_CONTENT_DELETE_CONTENT_PATH", "domain/delete");
define("NM_DOMAIN_ACCESS_REALM", "NM_DOMAIN_ACCESS_REALM");


//Contentcontent_multiple_choice
//Content Types
define("NM_CONTENT_DOMAIN", "content_domain");
define("NM_CONTENT_CHAPTER", "content_chapter");
define("NM_CONTENT_MULTIPLE_CHOICE", "content_multiple_choice");
define("NM_CONTENT_QUESTION_AND_ANSWER", "content_question_and_answer");
define("NM_BIBLIO", "biblio");
define("NM_INTERACTIVE_CONTENT", "h5p_content");
define("NM_FILE", "file");

//Course
//Content Types
define("NM_COURSE_NEWS", "courses_news");
define("NM_COURSE_DOCS", "courses_docs");
define("NM_COURSE_GROUP", "courses_group");
define("NM_COURSE", "courses_course");
define("NM_COURSE_FORUMTOPIC", "forum");
define("NM_COURSE_GENERIC_TASK", "courses_generic_task");
define("NM_COURSE_GENERIC_TASK_PATH", "course/tasks");
define("NM_COURSE_GENERIC_TASK_SOLUTION", "courses_generic_task_solution");
define("NM_COURSES_OVERVIEW_ID", 49);

define("NM_COURSE_DOC_PATH", "course/doc");
define("NM_COURSE_DOCS_PATH", "course/docs");
define("NM_COURSE_HOME_PATH", "course/home");
define("NM_COURSE_NEWS_PATH", "course/news");
define("NM_COURSE_INFO_PATH", "course/info");
define("NM_COURSE_GROUPS_PATH", "course/groups");
define("NM_COURSE_TEXT_PATH", "course/text");
define("NM_COURSE_BIBLIO_PATH", "course/biblio");
define("NM_COURSE_MEMBERS_PATH", "course/members");
define("NM_COURSE_FORUM_PATH", "course/forum");
define("NM_COURSE_FORUMCONTENT_PATH", "course/forumcontent");
define("NM_COURSE_ADMIN_PREFIX_PATH", "course/admin");

define("NM_COURSE_DEMO_LABEL", "[DEMO MODUS]");


//Tasks
define("NM_COURSES_TASK_DESCRIPTION", "0");
define("NM_COURSES_TASK_TASK", "1");
define("NM_COURSES_TASK_TIPS", "2");
define("NM_COURSES_TASK_CRITERIA", "3");
define("NM_COURSES_TASK_FORM", "4");

define("NM_COURSES_TASK_TYPE_SINGLE", "0");
define("NM_COURSES_TASK_TYPE_GROUP", "1");

define("NM_COURSES_TASK_WORKFLOW_DRAFT", "2");
define("NM_COURSES_TASK_WORKFLOW_SUBMITTED", "3");
define("NM_COURSES_TASK_WORKFLOW_ASSESSED", "4");

//Projects
//Content Types
define("NM_PROJECTS_RROJEKTORGANISATION", "projects_organization");
define("NM_PROJECTS_DOKUMENTATION", "projects_documentation");
define("NM_PROJECTS_KOOPERATIONSVEREINBARUNG", "projects_cooperation_agreement");
define("NM_PROJECTS_ZIELVEREINBARUNG", "projects_objective");
define("NM_PROJECTS_PROJEKTVORSCHLAG", "projects_proposal");
define("NM_PROJECTS_TAGEBUCH", "projects_blog");

define("NM_COURSE_PROJECTS_PATH", "projects/");

define("NM_COURSE_PROJECTS_PARTNERS_PATH", "projects/partners/");

//Videosafe Contenttype
define("NM_VIDEOSAFE_PATH", "videosafe");
define("NM_VIDEOSAFE_FOLDER", "videosafe_folder");
define("NM_VIDEOSAFE_VIDEO", "videosafe_video");

//Domains
//Contet Types
define("NM_SPACE", "spaces_space");


//Features..
//define('NM_COURSE_FEATURE_WIKI', $value)
define('NM_COURSE_FEATURE_FORUM', 'forum');
define('NM_COURSE_FEATURE_COURSE_GROUP_LOCK', 'course_group_lock');

define("NM_COURSES_ROLE_ADMINISTRATOR", "kurs-dozent");
define("NM_COURSES_ROLE_TUTOR", "kurs-tutor");
define("NM_COURSES_ROLE_STUDENT", "kurs-student");

//Roles
define("NM_ROLE_AUTOR", "Autor");
define("NM_ROLE_ADMIN", "administrator");
define("NM_ROLE_DOZENT", "Dozent");
define("NM_ROLE_STUDENT", "Student");
define("NM_ROLE_TEST_STUDENT", "Test Student");
define("NM_ROLE_TUTOR", "Tutor");
define("NM_ROLE_MODERATOR", "Moderator");

define("NM_ROLE_KOOPERATIONSPARTNER", "Kooperationspartner");

//Content
//Views
define("NM_VIEW_DOMAIN_MEDIA", "domain_media");


//Content
define("NM_CHAPTER_SEPARATOR", ".");


module_load_include('inc', 'custom_general', 'inc/functions');
module_load_include('inc', 'custom_general', 'inc/blocks');

/*
 * Context
 */

function custom_general_ctools_plugin_api($module, $api) {
  if ($module == 'context' && $api == 'plugins') {
    return array('version' => 3);
  }
}

/**
 * CTools plugin API hook for Context. Note that a proper entry in
 * hook_ctools_plugin_api() must exist for this hook to be called.
 */
function custom_general_context_plugins() {
  $plugins = array();
  $plugins['custom_general_condition_section_content'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'custom_general') . '/context_plugins',
      'file' => 'custom_general_condition_section_content.inc',
      'class' => 'custom_general_condition_section_content',
      'parent' => 'context_condition',
    ),
  );
  $plugins['custom_general_condition_section_courses'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'custom_general') . '/context_plugins',
      'file' => 'custom_general_condition_section_courses.inc',
      'class' => 'custom_general_condition_section_courses',
      'parent' => 'context_condition',
    )
  );
  $plugins['custom_general_condition_section_projects'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'custom_general') . '/context_plugins',
      'file' => 'custom_general_condition_section_projects.inc',
      'class' => 'custom_general_condition_section_projects',
      'parent' => 'context_condition',
    )
  );

  return $plugins;
}

/**
 * Registry hook for conditions & reactions.
 *
 * Each entry associates a condition or reaction with the CTools plugin to be
 * used as its plugin class.
 */
function custom_general_context_registry() {
  return array(
    'conditions' => array(
      'custom_general_condition_section_content' => array(
        'title' => t('Section Content is active'),
        'description' => t("Set this context when viewing parts of the <em>Content Section</em>"),
        'plugin' => 'custom_general_condition_section_content',
      ),
      'custom_general_condition_section_courses' => array(
        'title' => t('Section Courses is active'),
        'description' => t("Set this context when viewing parts of the <em>Courses Section</em>"),
        'plugin' => 'custom_general_condition_section_courses',
      ),
      'custom_general_condition_section_projects' => array(
        'title' => t('Section Projects is active'),
        'description' => t("Set this context when viewing parts of the <em>Projects Section</em>"),
        'plugin' => 'custom_general_condition_section_projects',
      ),
    ),
  );
}

/*
  function custom_general_context_page_reaction() {

  } */

function custom_general_init() {
  static $init;

  if ($init)
    return;

  $init = TRUE;

  // Execute the group type context condition all the time because we want
  // to use that condition to be able to check for "no group context."
  $plugin = context_get_plugin('condition', 'custom_general_condition_section_content');
  if ($plugin) {
    $plugin->execute2();
  }

  $plugin = context_get_plugin('condition', 'custom_general_condition_section_courses');
  if ($plugin) {
    $plugin->execute2();
  }


  $plugin = context_get_plugin('condition', 'custom_general_condition_section_projects');
  if ($plugin) {
    $plugin->execute2();
  }


  $group = og_context();
  if ($group) {

    $plugin = context_get_plugin('condition', 'custom_general_condition_section_content');
    if ($plugin) {
      $plugin->execute($group);
    }

    $plugin = context_get_plugin('condition', 'custom_general_condition_section_courses');
    if ($plugin) {
      $plugin->execute($group);
    }

    $plugin = context_get_plugin('condition', 'custom_general_condition_section_projects');
    if ($plugin) {
      $plugin->execute($group);
    }

    //30.04.2013 - 18:19 - SN
    //todo optimization needed ?
    //needs to be executed once again, because one context is set too late
    $plugin = context_get_plugin('condition', 'context_og_condition_member_status');
    if ($plugin) {
      $plugin->execute($group);
    }
  }
}

function custom_general_context_page_reaction() {
  
}


function custom_general_form_alter($form, $form_state, $form_id) {

  if ($form_id != "book_admin_edit")
    return;

  $plugin = context_get_plugin('condition', 'custom_general_condition_section_content');
  if ($plugin) {

    $plugin->execute2();
  }
}


/**
 * BIBLIO alter form, fix step 2
 * after selecting a "Publication Type" in a panel
 * (/domain/add/%/biblio) the selection is not being saved
 * 
 * form functions are called twice in panels, so im trying to cache the form_state for 
 * the second execution
 * [todo] move to section_courses
 */
function custom_general_form_biblio_node_form_alter(&$form, &$form_state, $form_id) {
  static $called = 0;

  //storing right values from first  call!
  if ($called == 0) {
    $called = 1;

    if (isset($_SESSION['onlinekurslabor']['biblio']['form_state_biblio_type'])) {
      $now = time();
      //unset session on new page call
      //dpm('call,now');
      //dpm($_SESSION['onlinekurslabor']['biblio']['timestamp']);
      //dpm($now);
      if ($now - $_SESSION['onlinekurslabor']['biblio']['timestamp'] > 2) {
        unset($_SESSION['onlinekurslabor']['biblio']);
      }
    }

    $node = isset($form['#noce']) ? $form['#node'] : null;
    $tid = !empty($form_state['biblio_type']) ? $form_state['biblio_type'] :
        ( isset($node->biblio_type) ? $node->biblio_type : 0);

    $step_two = !empty($tid);

    //dpm($step_two);
    if ($step_two) {
      $_SESSION['onlinekurslabor']['biblio']['form_state_biblio_type'] = $form_state;
      $_SESSION['onlinekurslabor']['biblio']['form'] = $form;
      $_SESSION['onlinekurslabor']['biblio']['timestamp'] = time('now');
      //dpm('time: ' . time('now'));
    }
  }

  //overriding strange values in every unnecessary additional call
  //coming from page/panels?! don't know.. quick fix
  if (isset($_SESSION['onlinekurslabor']['biblio']['form_state_biblio_type'])) {
    //dpm('setting form');
    $form_state = $_SESSION['onlinekurslabor']['biblio']['form_state_biblio_type'];
    $form = $_SESSION['onlinekurslabor']['biblio']['form'];
    //$form = drupal_get_form('form_biblio_node_form', $form_state);
    //unset($_SESSION['onlinekurslabor']['biblio']['form_state_biblio_type']);
  }
}

/**
 * Get the group id the node belongs to
 * 
 * @param type $referer_node
 * @return nid
 */
function _custom_general_get_group($referer_node) {
  $domain_id = NULL;
  //passed value can be FALSE
  if (!isset($referer_node) || $referer_node === FALSE) {
    return $domain_id;
  }

  //if referer is group -> nid == gid, else look up the gid
  if (og_is_group('node', $referer_node)) {
    $domain_id = $referer_node->nid;
  }
  else {
    //forum special case
    if ($referer_node->type == NM_COURSE_FORUMTOPIC) {
      $tid = ($referer_node->taxonomy_forums[LANGUAGE_NONE][0]['tid']);
      $term = taxonomy_term_load($tid);
      $course_nid = $term->og_group_ref ? $term->og_group_ref[LANGUAGE_NONE][0]['target_id'] : NULL;

      $domain_id = $course_nid;
    }
    else {
      $entities = og_get_entity_groups('node', $referer_node->nid);
      if (!empty($entities)) {
        $domain_id = current(current($entities));
      }
    }
  }


  return $domain_id;
}

//get breadcrumb items for domain by group id
/*
  function _section_content_get_domain_breadcrumb_items($group_get_id = NULL) {

  //get active group id, passed as get param
  $tmp_gid = isset($_GET['og_group_ref']) ? $_GET['og_group_ref'] : NULL;
  $group_get_id = isset($group_get_id) ? $group_get_id : $tmp_gid;


  if (!isset($group_get_id))
  return NULL;

  //build query items for breadcrumb items, to keep important get information in the url
  $item_options = array(
  'absolute' => TRUE,
  'query' => array(
  'og_group_ref' => $group_get_id,
  )
  );
  $node_overview = node_load(NM_DOMAIN_OVERVIEW_ID);
  $node_domain = node_load($group_get_id);

  $domain_overview_item = array(
  'title' => $node_overview->title,
  'href' => check_url(url('node/' . NM_DOMAIN_OVERVIEW_ID, $item_options)),
  'localized_options' => array(),
  );
  $active_domain_item = array(
  'title' => $node_domain->title,
  'href' => check_url(url('node/' . $group_get_id, $item_options)),
  'localized_options' => array(),
  );

  return array('domain_overview_item' => $domain_overview_item, 'active_domain_item' => $active_domain_item);
  }

 */

/**
 *  Implementation of hook_field_attach_form 
 */
/*
 * get og fields for file entities
 */

function _custom_general_get_file_og_fields($form, $form_state, $form_id) {
  $file = new stdClass();
  $file->type = 'video';

  $options = array(
    //specify the language, or use like this for the default language.
    'language' => field_valid_language(NULL),
    //IMPORTANT : the field you want to attach to the form
    'field_name' => 'og_group_ref'
  );

  $tmpform = array();
  $tmpform_state = array();

  field_attach_form('file', $file, $tmpform, $tmpform_state);
  $og_field = array('og_group_ref' => $tmpform['og_group_ref']);

  //add og_group_ref field to the upload form
  //$og_field = (array) _field_invoke_default('form', 'file', $file, $form, $form_state, $options);

  return $og_field;
}

/**
 * get referer nid in Mediabrowser
 * 
 */
function _media_browser_get_referer_nid() {
  $referer_args = array();

  $url_data = drupal_parse_url($_SERVER['HTTP_REFERER']);
  $referer_args['path'] = substr(parse_url($url_data['path'], PHP_URL_PATH), 1);
  //if no nid is set, a new node is being created, so we need the passed og_group_ref
  if (isset($url_data['query']['og_group_ref']) && is_numeric($url_data['query']['og_group_ref'])) {
    $referer_args['nid'] = $url_data['query']['og_group_ref'];
  }
  else {
    $referer_args['nid'] = arg(2, $referer_args['path']);
    $referer_args['nid'] = is_numeric($referer_args['nid']) ? $referer_args['nid'] : NULL;
  }

  return $referer_args['nid'];
}

function _custom_general_theme_tools_block($tool_links, $id = "", $class = "section_nav_tools", $span_grouping = 12) {

  //$output = '<div id="' . $id . '-container">';
  //$output = '<div id="' . $id . '-container" class="navbar">';
  //built up group arary
  $groups = array();
  foreach ($tool_links as $tl) {
    if (isset($tl['group']) && (isset($tl['group']['root']) && $tl['group']['root'])) {
      $groups[$tl['group']['gid']] = $tl['group'];
    }
  }

  $span_class = 'span' . $span_grouping;

  //$output .= '<div class="navbar-inner">';
  $output = '<div id="' . $id . '-container" class="' . $class . ' row-fluid">';
  //$output .= '<div id="' . $id . '-icon"></div>';
  //$output .= '<ul id="' . $id . '" class="' . $class . ' nav">';


  $span_counter = 0;

  if (!empty($groups)) {
    foreach ($groups as &$group) {
      $group['items'][] = _section_courses_get_group_root($group, $tool_links);
      $sub_items = _section_courses_get_group_others($group, $tool_links);
      foreach ($sub_items as $su) {
        $group['items'][] = $su;
      }
    }
    unset($group);
  }

  //if group is set - assume that we want to have a vertical toolbar
  if (!empty($groups)) {
    //$output .= '<div class="span12"></div>';
    //$output .= '<div class="span4">';
    foreach ($groups as $g) {
      $group_items = ($g['items']);
      $output .= '<div class="row-fluid">';
      $output .= '<div class="span12">';
      $output .= '<ul>';
      $depth = 0;
      foreach ($group_items as $gi) {
        if ($depth > 0) {
          if (isset($gi['attributes']['class'])) {
            $gi['attributes']['class'][] = 'toolbar_hidden';
          }
          else {
            $gi['attributes']['class'] = array('toolbar_hidden');
          }
        }
        $attributes = "";
        if (isset($gi['attributes'])) {
          $attributes = drupal_attributes($gi['attributes']);
        }

        //$output .= '<li '.$attributes.'>' . $tl['link'] . '</li>';
        $output .= '<li ' . $attributes . '>' . $gi['link'] . '</button>';

        $depth++;
      }
      $output .= '</ul>';
      $output .= '</div>';
      $output .= '</div>';
    }
    //$output .= '</div>';
    //$output .= '</div>';
  }
  //no groups configured - render horizontal toolbar
  else {
    foreach ($tool_links as $tl) {

      $append = "";
      $prepend = "";

      if ($span_counter % ($span_grouping) == 0) {
        $prepend = '<ul class="' . $span_class . '">';
      }
      if ((($span_counter % $span_grouping) == $span_grouping - 1) || $span_counter == count($tool_links) - 1) {
        $append = '</ul>';
      }

      $output .= $prepend;
      $attributes = "";
      if (isset($tl['attributes'])) {
        $attributes = drupal_attributes($tl['attributes']);
      }

      if ($span_counter == 0) {
        $output .= '<div id="' . $id . '-icon"></div>';
      }
      //$output .= '<li '.$attributes.'>' . $tl['link'] . '</li>';
      $output .= '<li ' . $attributes . '>' . $tl['link'] . '</li>';

      $output .= $append;

      $span_counter++;
    }
  }

  //$output .= '</ul>';
  //$output .= '<div id="'.$id.'-toolbar"></div>';
  //
  //$output .= '</div>';
  //$output .= '</div>';
  $output .= '</div>';

  return $output;
}

function _section_courses_get_group_root($group, $tool_links) {
  foreach ($tool_links as $tl) {
    if (!empty($tl['group']) && (isset($tl['group']['root']) && $tl['group']['root']) && $tl['group']['gid'] == $group['gid']) {
      return $tl;
    }
  }
  return NULL;
}

function _section_courses_get_group_others($group, $tool_links) {
  $result = array();

  foreach ($tool_links as $tl) {
    if (!empty($tl['group']) && (!isset($tl['group']['root']) || !$tl['group']['root']) && $tl['group']['gid'] == $group['gid']) {
      $result[] = $tl;
    }
  }
  return $result;
}

/**
 * Implements hook_wysiwyg_plugin
 * @param type $editor
 * @param type $version
 * @return type
 */
function custom_general_wysiwyg_plugin($editor, $version) {

  _linkit_add_settings($editor);

  //css rules
  drupal_add_css(drupal_get_path('module', 'custom_general') . '/css/wysiwyg.css');

  switch ($editor) {
    case 'ckeditor':
      return array(
        'custom_general_plugin' => array(
          'path' => drupal_get_path('module', 'custom_general') . '/wysiwyg_plugin',
          'buttons' => array(
            'biblio_button' => t('Biblio'),
          ),
          'load' => TRUE,
        ),
      );
      break;
  }
}

/**
 * Implements hook_menu
 * 
 * @return array
 */
function custom_general_menu() {

  $items = array();

  $items['admin/biblio_dashboard'] = array(
    'title' => 'Biblio',
    'description' => 'Biblio Auswahl',
    'page callback' => '_custom_general_biblio_dashboard',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'page arguments' => array(2),
      //'theme callback' => '_linkit_dashboard_theme',
  );

  $items['admin/onlinekurslabor'] = array(
    'title' => 'Onlinekurslabor',
    'access callback' => 'custom_general_user_is_okl_admin',
    'access arguments' => array(array('administrator')),
    'page callback' => 'custom_general_onlinekurslabor_admin_page',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function custom_general_onlinekurslabor_admin_page() {
  return "Onlinekurslabor Setting Page";
}

function custom_general_menu_alter(&$items) {
  // Example - disable the page at node/add
  $items['node']['access callback'] = FALSE;
}

function _custom_general_biblio_dashboard() {
  /**
   * Creates the dashboard.
   */
  $form = drupal_get_form('_custom_general_biblio_dashboard_form');
  print drupal_render($form);
  drupal_exit();
}

/**
 * Implements hook_form().
 */
function _custom_general_biblio_dashboard_form($form, &$form_state) {
  $profile = linkit_profile_load("biblio");


  if (is_null($profile)) {
    drupal_set_message(t('You need a linkit profile named <em>biblio</em> to continue!'), 'error');
    return $form;
  }

  $form['biblio_search'] = array(
    //'#prefix' => '<div>' . l('Biblio hinzufügen', 'node/add/biblio', array('attributes' => array('target' => '_blank'))) . '</div>',
    '#type' => 'textfield',
    //'#title' => t('Search Biblio'),
    //'#description' => t('Start typing to find a biblio entry. Use the arrow keys to navigate.'),
    '#maxlength' => 255,
    '#size' => 60,
    '#default_value' => '',
    '#weight' => -10,
    '#attributes' => array('placeholder' => 'Suche - Biblio Titel'),
  );

  $form['biblio_tag'] = array(
    '#type' => 'textfield',
    //'#title' => t('Biblio-ID (nid)'),
    '#required' => TRUE,
    '#maxlength' => NULL,
    '#size' => 60,
    '#default_value' => '',
    '#weight' => -1,
    '#attributes' => array('placeholder' => 'Biblio ID (nid)'),
  );

  $form['biblio_insert'] = array(
    '#type' => 'submit',
    '#value' => 'Biblio einfügen',
    '#suffix' => '<a id="biblio-cancel" class="btn" href="#">' . t('Cancel') . '</a>',
    '#weight' => 100,
    '#attributes' => array('class' => array('btn', 'btn-primary')),
  );

  return $form;
}

function custom_general_preprocess_page(&$variables) {
  //include js needed for every page
  drupal_add_js(drupal_get_path('module', 'custom_general') . "/js/custom_general.js");
  drupal_add_js(drupal_get_path('module', 'custom_general') . "/js/jquery.autogrow-textarea.js");
  drupal_add_js(drupal_get_path('module', 'custom_general') . "/js/jquery.knob.js");
  drupal_add_js(drupal_get_path('module', 'custom_general') . "/js/spin.js");

  drupal_add_library('system', 'ui.progressbar');
}

function custom_general_append_active_class($path, &$options) {
  // Append active class.
  if (($path == $_GET['q'] || ($path == '<front>' && drupal_is_front_page())) && (empty($options['language']) || $options['language']->language == $language_url->language)) {
    $options['attributes']['class'][] = 'active';
  }
}

/**
 * Implements hook_block_info().
 */
function custom_general_block_info() {
  $blocks = array();
  $blocks['custom_general_top_nav'] = array(
    'info' => t('Top navigation items'),
  );
  $blocks['custom_general_space'] = array(
    'info' => t('Custom General - Space'),
  );


  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function custom_general_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'custom_general_top_nav' :
      $block['content'] = _custom_general_theme_top_nav();
      break;
    case 'custom_general_space' :
      $block['content'] = _custom_general_theme_space();
      break;
  }

  return $block;
}

/**
 * Implements hook_field_default_fields_alter().
 *
 * Alter the default fields right before they are cached into the database.
 *
 * @param &$fields
 *   By reference. The fields that have been declared by another feature.
 */

/**
 * Implements hook_field_default_field_bases_alter().
 * note: Features hook
 *
 * Set default images here
 * Alter the default fields right before they are cached into the database.
 *
 * @param &$fields
 *   By reference. The fields that have been declared by another feature.
 */
function custom_general_field_default_field_bases_alter(&$fields) {
  $source_dir = drupal_get_path('module', 'custom_general') . '/images/default_images';
  $field_default_images = array(
    // Field Base uses the field name
    'field_photo' => 'noprofile_default.jpg',
    'field_course_header' => 'course_header_default.jpg',
    'field_course_picture' => 'course_header_default.jpg',
  );
  foreach ($field_default_images as $field_name => $filename) {
    $source = $source_dir . '/' . $filename;
    $destination = 'default_images/' . $filename;
    if (isset($fields[$field_name])) {
      _custom_general_set_default_image($fields[$field_name], $filename, $source, $destination);
    }
  }
}

/**
 * Custom function to set the default image.
 * (It has an _ at the beginning to make sure it never accidentally gets fired as a hook)
 *
 * @param  array $field
 * @param  string $filename Filename of the source image.
 * @param  string $source Filepath of the source image.
 * @param  string $destination Filepath you want to save to.
 */
function _custom_general_set_default_image(&$field, $filename, $source, $destination) {
  // See if a default image hasn't been set for this field yet
  //if (empty($field['settings']['default_image'])) {
  // Dynamically set the user default image on the field
  $destination = file_default_scheme() . '://' . $destination;
  // Check to see if it exists already
  $result = db_select('file_managed', 'f')
      ->fields('f', array('fid'))
      ->condition('f.uri', $destination)
      ->execute();
  $fid = $result->fetchField();
  // Simulate an upload of the default user image
  if (!$fid && file_exists($source)) {
    $file = new stdClass;
    $file->filename = $filename;
    $file->timestamp = REQUEST_TIME;
    $file->uri = $source;
    $file->filemime = file_get_mimetype($source);
    $file->uid = 1;
    $file->status = 1;
    $file = file_copy($file, 'public://default_images', FILE_EXISTS_REPLACE);

    if (!$file) {
      watchdog('custom general', 'Default image could not be set', null, WATCHDOG_ERROR);

      return;
    }


    $fid = $file->fid;
  }
  // field_config key no longer seems to exist.
  // $field['field_config']['settings']['default_image'] = (string) $fid;
  // Use this instead.
  $field['settings']['default_image'] = (string) $fid;
  //}
}

/**
 * fix realname
 * Implements hook_user_insert().
 */
/*
function custom_general_user_insert(&$edit, $account, $category) {
  //$account = user_load($account, TRUE);
  realname_update($account);
}*/


/**
 * Implementation of hook_mail_alter().
 * Here we allow the site name to be used as the senders name for outgoing email.
 * see http://drupal.org/node/209672
 */
function custom_general_mail_alter(&$message){
  $default_from = variable_get('site_mail', ini_get('sendmail_from'));

  if($message['from'] == $default_from){
    $default_from = 'onlinekurslabor@medienlabor-uni-augsburg.de';
    $message['headers']['Reply-To'] = '"'. variable_get('site_name', 'Drupal') .'" <'. $default_from .'>';
  }
}


/**
 * helper function for linkit autocomplete
 * checks if referer is one of context relevant nodes
 * todo project
 * @return bool
 */
function _custom_general_referer_node_add() {
  //check linkin ajax requests
  if (
    (arg(0) == 'admin' && strstr(arg(1), "_dashboard")) ||
    (arg(0) == 'section_content' && arg(1) == 'tasks' && arg(2) == 'autocomplete') ||
    (arg(0) == 'h5p_integration' && arg(1) == 'item' && arg(2) == 'autocomplete')
  ) {
    $referer_url = drupal_parse_url($_SERVER['HTTP_REFERER']);
    $referer_url['path'] = substr(parse_url($referer_url['path'], PHP_URL_PATH), 1);

    $referer_path = $referer_url['path'];
    if (arg(0, $referer_path) == 'node' &&
      arg(1, $referer_path) == 'add'
      && in_array(arg(2, $referer_path), array(
        "courses-course",
        "content-domain"
      ))
    ) {
      //FORCE no results
      return TRUE;
    }
  }

  return FALSE;
}

/**
 * @param \QueryAlterableInterface $query
 */
function custom_general_query_alter(QueryAlterableInterface $query) {
  if ($query->hasTag('linkit_entity_autocomplete')) {

    //node add special case
    //adding domain, course

    //check linkin ajax requests
    //return empty list result, when adding course and domain. no context is set yet.
      //so no course/domain h5p and other content exist.
      if (_custom_general_referer_node_add()) {
        $query->condition("node.nid", "-1");
      }


    $domain = _section_content_get_active_domain(TRUE);
    $course = _section_courses_get_active_course(TRUE);

    $group = NULL;
    if ($domain) {
      $group = $domain;
    }
    else {
      if ($course) {
        $group = node_load(_section_courses_course_get_domain_id($course));
      }
    }

    if ($group) {
      //dpm((string) $query);
      $ogm_alias = $query->leftJoin('og_membership', 'ogm', 'ogm.etid = node.nid'); // AND ogm.tid = :entity_id
      $query->condition("$ogm_alias.gid", $group->nid); // AND ogm.tid = :entity_id
    }
  }

}

