<?php

/**
 * @file
 *   Integrates Rules with Statuses Comments.
 */

/*
 * Implements hook_fbss_comments_after_save().
 */
function fbss_comments_rules_fbss_comments_after_save($comment, $edit) {
  if ($edit) {
    rules_invoke_event('fbss_comments_edit', $comment);
  }
  else {
    rules_invoke_event('fbss_comments_save', $comment);
  }
}

/*
 * Implements hook_fbss_comments_delete().
 */
function fbss_comments_rules_fbss_comments_delete($cid) {
  $comment = fbss_comments_load($cid);
  rules_invoke_event('fbss_comments_delete', $comment);
}
