<?php

/**
 * @file
 *   Integrates Statuses with the Domain Access module.
 */

/**
 * Implements hook_statuses_save().
 */
function fbss_domain_statuses_save($status, $context, $edit, $options) {
  if (!$edit) {
    $domain = domain_get_domain();
    $record = (object) array('sid' => $status->sid, 'domain_id' => $domain['domain_id']);
    drupal_write_record('fbss_domain', $record);
  }
}

/**
 * Implements hook_statuses_delete().
 */
function fbss_domain_statuses_delete($status, $meta) {
  db_delete('fbss_domain')
    ->condition('sid', $status->sid)
    ->execute();
}

/**
 * Implements hook_views_api().
 */
function fbss_domain_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'fbss_domain'),
  );
}
