<?php
function private_msg_menu_alter(&$items) {
    
  $items['messages/delete/%privatemsg_thread/%privatemsg_message']['access callback']  = 'privatemsg_user_access';
          
    
}

function privatemsg_okl_privatemsg_thread_operations() {
  $operations = array();
    
  $roles[] = ($user->roles);
    if (in_array( NM_ROLE_ADMIN , $roles ) && privatemsg_user_access('delete privatemsg')) {
    $operations['delete'] = array(
      'label' => t('Delete'),
      'callback' => 'privatemsg_thread_change_delete',
      'callback arguments' => array('delete' => 1),
      'undo callback' => 'privatemsg_thread_change_delete',
      'undo callback arguments' => array('delete' => 0),
      'button' => TRUE,
    );
  }
  return $operations;
}