<?php

/**
 * @file
 * sidebar fuer den h5p-player
 */

/**
 * @ingroup image
 * @{
 */

/**
 * Implements hook_init().
 */
function h5pannotationlist_init() {
$nid = (arg(0) == 'node' && is_numeric(arg(1))) ? arg(1) : NULL;

		drupal_add_js(array('h5psidebar' => array('json_video_id' => 'cid-'.$nid)), 'setting');
		      drupal_add_js(drupal_get_path('module', 'h5pannotationlist') .'/assets/javascript/sprintf.js');
   drupal_add_js(drupal_get_path('module', 'h5pannotationlist') .'/assets/javascript/main.js');

   drupal_add_css(drupal_get_path('module', 'h5pannotationlist') . '/assets/css/main.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
   drupal_add_css(drupal_get_path('module', 'h5pannotationlist') . '/assets/css/font-awesome.min.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
  }
 
/**
 * @} End of "ingroup image".
 */
