<?php

/*
 * book-navigation auf hilfe-start raus
 */
function section_help_node_view($node, $view_mode, $langcode) {

    $help_bid = variable_get('okl_help_bid', NM_HELP_BID);
    if (@$node->book['bid'] == $help_bid) {
        if ($node->nid == $help_bid) {
            unset($node->content['book_navigation']);
        }
    }
}

/* hook_preprocess_page
 * header fuer hilfe rendern */
function section_help_preprocess_page(&$variables) {
    $help_bid = variable_get('okl_help_bid', NM_HELP_BID);
    $node = $variables['node'];
   
    if (!empty($node)) {
        if ($node->nid == $help_bid || $variables[node]->book[bid] == $help_bid) {
             $fid =  variable_get('okl_help_header_fid', NM_HELP_HEADER_FID);
             
            $variables['page']['header']['help_header_section'] = array(
                //todo FID laden und einen header wie in kurs/projectsection bauen
                '#markup' => '<a href="/help"><img src="/sites/all/themes/bootstrap_onlinekurslabor/images/header-help.jpg" title="<?=$title?>"></a>',
                '#weight' => -10
            );
            unset($variables['page']['header']['custom_general_custom_general_space']);
            $variables['title'] = '';
            #dpm($variables);
        }
    }
}
