<?php

/**
* Implementation of hook_rules_event_info().
*/
/*
function section_courses_rules_event_info() {
  return array(
    'section_courses_send_mail_filter_by_role' => array(
      'label' => t('Send Email to users with a sepecific role.'),
      'module' => 'section_courses',
      'arguments' => array(
        'recipient' => array('type' => 'user', 'label' => t('User')),
      ),
    ),
  );
}

/**
 * Rule action foo.
 */
/*
function section_courses_send_mail_filter_by_role() {
  drupal_set_message("I'm a foo for you!");
}*/