<?php

/*
 * Redirecting from node view to specific panel view
 *
 */

function onlinekurslabor_redirect_node_view($node, $view_mode, $langcode) {

  return;
  //check if we are in node/%nid/context
  if (arg(0) != 'node' || arg(2) == 'revisions') {
    return;
  }
  /*
   *  NEW LOGICs
   * 18.09.2014 - 17:34 - SN
   */

  //redirection rules for domains and projects
  switch ($node->type) {
        case NM_CONTENT_DOMAIN:
        case NM_CONTENT_CHAPTER:
        case NM_INTERACTIVE_CONTENT:
            if($view_mode ==  'full')
            {
                /*das ist alt... bei h5p wird in den themenbereich umgeleitet. aber nur wenns vollansicht ist. */
                drupal_goto(NM_CONTENT_TEXT_PATH . '/' . $node->nid);
            }
            break;
        //projects
        case NM_PROJECTS_KOOPERATIONSVEREINBARUNG:
            $ca = $node;
            $proposal = node_load($ca->field_ca_proposal_ref[LANGUAGE_NONE][0]['target_id']);
            $partner_nid = _custom_general_get_group($proposal);
            $path = "projects/partners/" . $partner_nid . "/" . $proposal->nid . "/cockpit/" . $ca->nid;

            drupal_goto($path);
            break;

        case NM_PROJECTS_RROJEKTORGANISATION:
            $partner = $node;
            $path = "projects/partners/" . $partner->nid;

            drupal_goto($path);
            break;

        case NM_PROJECTS_PROJEKTVORSCHLAG:
            $proposal = $node;
            $partner_nid = _custom_general_get_group($proposal);
            $path = "projects/partners/" . $partner_nid . "/" . $proposal->nid;

            drupal_goto($path);
            break;

        case NM_PROJECTS_TAGEBUCH:
            $blog = $node;
            $ca = node_load(_custom_general_get_group($blog));

            $proposal = node_load($ca->field_ca_proposal_ref[LANGUAGE_NONE][0]['target_id']);
            $partner_nid = _custom_general_get_group($proposal);
            $path = "projects/partners/" . $partner_nid . "/" . $proposal->nid . "/cockpit/" . $ca->nid;

            //redirect to the right position
            $options = array();
            $options['fragment'] = 'node-' . $blog->nid;

            drupal_goto($path, $options);
            break;
        case NM_VIDEOSAFE_VIDEO:
        case NM_VIDEOSAFE_FOLDER:
            drupal_goto(NM_VIDEOSAFE_PATH . '/' . $node->nid);
            break;
        
    }

    $active_course = _section_courses_get_active_course();


  //21.10.2015 - 12:35 - SN
  //try to build context
  if(empty($active_course)) {
    switch ($node->type) {
      case NM_COURSE:
        $active_course = clone $node;
        break;
      default:
        if(!empty($node->og_group_ref[LANGUAGE_NONE][0]['target_id'])) {
          $tmp_node = node_load($node->og_group_ref[LANGUAGE_NONE][0]['target_id']);
          if($node->type == NM_COURSE){
            $active_course = clone $tmp_node;
          }
        }
        if(!empty($node->field_generic_task[LANGUAGE_NONE][0]['target_id'])) {
          $tmp_node_task = node_load($node->field_generic_task[LANGUAGE_NONE][0]['target_id']);
          if(!empty($tmp_node_task->og_group_ref[LANGUAGE_NONE][0]['target_id'])) {
            $tmp_node = node_load($tmp_node_task->og_group_ref[LANGUAGE_NONE][0]['target_id']);
            if($tmp_node->type == NM_COURSE){
              $active_course = clone $tmp_node;
            }
          }
        }
        break;
      }
  }



  if ($active_course) {
    switch ($node->type) {
      case NM_COURSE:
        //course
        drupal_goto(NM_COURSE_HOME_PATH . '/' . $active_course->nid);
        break;
      case NM_COURSE_NEWS:
        //news
        drupal_goto(NM_COURSE_NEWS_PATH . '/' . $active_course->nid . '/' . $node->nid);
        break;
      case NM_COURSE_DOCS:
        //docs
        drupal_goto(NM_COURSE_DOC_PATH . '/' . $active_course->nid . '/' . $node->nid);
        break;
      case NM_COURSE_GENERIC_TASK:
        //Task
        drupal_goto(NM_COURSE_GENERIC_TASK_PATH . '/' . $active_course->nid . '/' . $node->nid . '/solution');
        break;
      case NM_COURSE_GENERIC_TASK_SOLUTION:

        //Solution
        $tid = $node->field_generic_task[LANGUAGE_NONE][0]['target_id'];
        //Redirect Admins, Dozenten, Tutoren to solution
        if (section_courses_instructors_tools_access()) {
          drupal_goto(NM_COURSE_GENERIC_TASK_PATH . '/' . $active_course->nid . '/' . $tid . '/solution/' . $node->uid);
        }
        else {
          drupal_goto(NM_COURSE_GENERIC_TASK_PATH . '/' . $active_course->nid . '/' . $tid . '/solution');
        }
        //drupal_access_denied();
        break;
      case NM_COURSE_GROUP:
        //Course Group
        drupal_goto(NM_COURSE_GROUPS_PATH . '/' . $active_course->nid . '/' . $node->nid);
        break;
      case NM_COURSE_FORUMTOPIC:
        //forum
        drupal_goto(NM_COURSE_FORUMCONTENT_PATH . '/' . $active_course->nid . '/' . $node->nid);
        break;
    }
  }
  else {
    //if no active course can be found
    switch ($node->type) {
      case NM_COURSE_FORUMTOPIC:
        //deny access, if forum is not assigned to any special course (in general)
        //drupal_access_denied();
        break;
      //redirect rules for domains and chapters
      case NM_CONTENT_DOMAIN:
      case NM_CONTENT_CHAPTER:
      case NM_INTERACTIVE_CONTENT:
        //nur bei vollansicht - embed hat dann kein redirect
        if($view_mode ==  'full')
            {
              drupal_goto(NM_CONTENT_TEXT_PATH . '/' . $node->nid);
            }
        break;
    }
  }
}

/*
 *
 */

function onlinekurslabor_redirect_preprocess_page($variables) {
  global $user;

  return;
  //assuming viewing a panel page
  if (page_manager_get_current_page()) {

    //note: node type needs to be checked in variants "Selection rules"
    //user in news section
    if (strstr(current_path(), NM_COURSE_NEWS_PATH)) {

      $active_course = _section_courses_get_active_course();
      $news_nid = arg(3);
      $news_node = node_load($news_nid);
      $group_nid = _custom_general_get_group($news_node);
      //news is assigned to another course
      if ($group_nid != $active_course->nid) {
        drupal_goto(NM_COURSE_HOME_PATH . '/' . $active_course->nid);
      }
    }

    //user in text section
    if (strstr(current_path(), NM_COURSE_TEXT_PATH)) {

      $active_course = _section_courses_get_active_course();
      $domain_ref = _section_courses_course_get_domain_id($active_course); //$active_course->field_domain_ref[LANGUAGE_NONE][0]['target_id'];

      $text_nid = arg(3);
      $text_node = node_load($text_nid);

      //chapter/domain is not the one chosen for the active course
      if (isset($text_node->book) && $text_node->book['bid'] != $domain_ref) {

        drupal_goto(NM_COURSE_TEXT_PATH . '/' . $active_course->nid . '/' . $domain_ref);
      }
    }

    //user in document section
    //note: course/doc is part of course/docs path...
    if (strstr(current_path(), NM_COURSE_DOC_PATH) && !strstr(current_path(), NM_COURSE_DOCS_PATH)) {

      $active_course = _section_courses_get_active_course();
      $docs_nid = arg(3);
      $docs_node = node_load($docs_nid);
      $group_nid = _custom_general_get_group($docs_node);
      //news is assigned to another course
      if ($group_nid != $active_course->nid) {
        drupal_goto(NM_COURSE_DOCS_PATH . '/' . $active_course->nid);
      }
    }



    //user is in course group section
    if (strstr(current_path(), NM_COURSE_GROUPS_PATH)) {
      //viewing group overview
      //get course group if available, else show overview
      $course_group_nid = _section_courses_student_get_coursegroup_gid();

      //avoid infinite loop if we already are on proper course group page
      if ($course_group_nid && $course_group_nid != arg(3)) {
        drupal_goto(NM_COURSE_GROUPS_PATH . '/' . arg(2) . '/' . $course_group_nid);
      }
    }

    //user is in task section
    if (strstr(current_path(), NM_COURSE_GENERIC_TASK_PATH) && arg(4) == "solution") {
      //permit others than authorized users to access paramter arg(5)
      $access = section_courses_tutor_tools_access();
      $solution_uid = arg(5);
      if (!$access && isset($solution_uid)) {
        drupal_goto(NM_COURSE_GENERIC_TASK_PATH . '/' . arg(2) . '/' . arg(3) . '/solution');
      }
    }

    //user is in forum section
    if (strstr(current_path(), NM_COURSE_FORUM_PATH) && !strstr(current_path(), NM_COURSE_FORUMCONTENT_PATH)) {
      //permit others than authorized users to access paramter arg(5)
      $active_course = _section_courses_get_active_course();
      $f_tid = arg(3);
      $course_forum_term = _section_courses_get_forum_term($active_course);

      //check if current form tid is child of course main forum_tid
      $parents = taxonomy_get_parents_all($f_tid);
      $is_parent = FALSE;
      if ($f_tid == $course_forum_term->tid) {
        $is_parent = TRUE;
      }
      else {
        foreach ($parents as $parent) {
          if ($parent->tid == $course_forum_term->tid) {
            $is_parent = TRUE;
            break;
          }
        }
      }

      //if selected term tid is NOT a child of course forum
      if (!$is_parent) {
        drupal_goto(NM_COURSE_FORUM_PATH . '/' . $active_course->nid . '/' . $course_forum_term->tid);
      }
    }
  }
}
