<?php

/**
 * navigation items for leftside space navigation
 * @return string
 */
function _section_spaces_get_navigation_items() {
  $navigation_items = array(
    'Home',
    'Kurse',
    'Themen',
    'Partner'
  );

  return $navigation_items;
}

/**
 * Implements hook_block_info().
 */
function section_spaces_block_info() {
  $blocks = array();

  $blocks['space_header_section'] = array(
    'info' => t('Space Header Secton'),
  );
  $blocks['space_navigation'] = array(
    'info' => t('Space Navigation'),
  );
  $blocks['space_main'] = array(
    'info' => t('Space Main'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function section_spaces_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'space_header_section' :
      $block['content'] = _section_spaces_header_view();
      break;

    case 'space_navigation' :
      $block['content'] = _section_spaces_navigation_view();
      break;
    case 'space_main' :
      $block['content'] = _section_spaces_main_view();
      break;
  }

  return $block;
}

function _section_spaces_header_view() {
  global $user;
  $user_uid = $user->uid;

  $block = array();
  $active_section = _section_space_get_active_section();

  if (!isset($active_section) || empty($active_section))
    return array();

  if ($active_section) {
    $output = "";
    $output .= '<div style="position:relative">';

    $output .= '<div id="space_header" class="row">';
    $output .= '<div class="col-md-12">';

    $output .= '<div id="space_header_title">';
    $output .= '<h1>';
    $output .= $active_section->title;
    $output .= '</h1>';

    $output .= '</div>';

    //header here
    $header_pic = '';
    if (isset($active_section->field_space_header)) {
      $field_view = field_view_field('node', $active_section, 'field_space_header', array('settings' => array('image_style' => 'course_header')));
      $uri = $field_view['#items'][0]['uri'];
      $url_array = file_create_url($uri);
      $url = parse_url($url_array);
      $path = $url['path'];
      $header_pic = '<div style="
        background-image:url(' . $path . ');
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover; 
        height:200px;
        ">
        </div>';
      $header_pic .= '<div style="
        background-color:#000;
        opacity:0.2;
        height:200px;
        z-index:1;
        position:absolute;
        width:100%;
        top:0;
        ">
        </div>';
    }
    $output .= $header_pic;

    $output .= '</div>';
    $output .= '</div>';

    //container
    $output .= "</div>";

    $block = array(
      'content' => array(
        '#type' => 'markup',
        '#markup' => $output,
    ));
  }

  return $block;
}

function _section_spaces_navigation_view() {
  global $user;

  $navigation_items = _section_spaces_get_navigation_items();

  $user_uid = $user->uid;

  $block = array();
  $active_section = _section_space_get_active_section();

  if (!isset($active_section) || empty($active_section))
    return array();

  $i = 0;
  if ($active_section) {
    $output = "";
    $output .= '<div style="position:relative" class="nav_tabbox">';
    foreach ($navigation_items as $item) {
      $active_class = ($i == 0) ? 'active' : '';
      $output .= '<div class="' . $active_class . '">';
      $output .= '<a href = "#" class="tab ' . drupal_html_class($item) . '">';
      $output .= $item;
      $output .= '</a>';
      $output .= '</div>';

      $i++;
    }

    $output .= '</div>';

    $block = array(
      'content' => array(
        '#type' => 'markup',
        '#markup' => $output,
    ));
  }

  return $block;
}

/**
 * Main Space View containing content for all needed content 
 * which is controlled from navigation bar items
 * @return array
 */
function _section_spaces_main_view() {

  $navigation_items = _section_spaces_get_navigation_items();

  $block = array();
  $active_section = _section_space_get_active_section();

  if (!isset($active_section) || empty($active_section))
    return array();

  if ($active_section) {
    $output = "";
    $output .= '<div style="position:relative" class="space_main_container">';
    $i = 0;

    foreach ($navigation_items as $item) {
      $active_class = ($i == 0) ? 'active' : '';

      $output .= '<div class = "tabpanel ' . drupal_html_class($item) . ' ' . $active_class . '">';

      $output .= call_user_func('section_spaces_main_' . drupal_html_class($item) . '_view');

      $output .= '</div>';
      $i++;
    }

    $output .= '</div>';

    $block = array(
      'content' => array(
        '#type' => 'markup',
        '#markup' => $output,
    ));
  }

  return $block;
}

function _section_space_get_active_section($reset = FALSE) {
  static $space;

  if (!isset($space) || $reset) {

    if (arg(0) == "space") {
      $space = FALSE;
      $node = node_load(arg(1));
    }
    else {
      $node = menu_get_object();
    }

    if ($node) {
      $space = $node;
    }

    if (is_object($node) && in_array($node->type, array(NM_SPACE))) {
      $space = node_load(_custom_general_get_group($node));
    }
    /*
      if (!isset($space)) {
      $c_nid = check_plain(arg(2));
      $space = is_numeric($c_nid) ? node_load($c_nid) : NULL;
      } */

    if (!empty($space) && $space->type == NM_SPACE) {

      return $space;
    }

    $space = FALSE;
  }

  return $space;
}

/*
 *  Add block programmatically
 */
/*
 * Implements hook_system_info_alter().
 */

//add course header 
//16.07.2013 - 11:58 - SN - now done by context module
function section_spaces_preprocess_page(&$vars) {
  $active_section = _section_space_get_active_section();

  if ($active_section) {

    drupal_add_js(drupal_get_path('module', 'section_spaces') . "/section_spaces.js");
    drupal_add_css(drupal_get_path('module', 'section_spaces') . "/section_spaces.css");

    $block = module_invoke('section_spaces', 'block_view', 'space_header_section');
    $vars['page']['header']['space_header_section'] = array(
      '#markup' => render($block),
      '#weight' => -10
    );

    uasort($vars['page']['header'], 'element_sort');
  }
}

/*
 * main tab views
 */

function section_spaces_main_home_view() {
  $output = '';

  $active_section = _section_space_get_active_section();
  if (isset($active_section->field_space_home)) {
    $field_view = field_view_field('node', $active_section, 'field_space_home', array('label' => 'hidden'));
    $output .= render($field_view);
  }

  return $output;
}

function section_spaces_main_kurse_view() {
  $output = '';

  $active_section = _section_space_get_active_section();
  if (isset($active_section->field_courses_ref)) {

    foreach ($active_section->field_courses_ref[LANGUAGE_NONE] as $course_id) {

      $course_node = node_load($course_id['target_id']);
      $vars = array();
      //$vars['image'] = '<img alt="" src="/sites/all/themes/bootstrap_onlinekurslabor/images/homepage/2_studierende_oT.png"  class="col-md-12" />';
      if (isset($course_node->field_course_picture)) {
        //$field_items = field_get_items('node', $active_course, 'field_course_header');
        $field_view = field_view_field('node', $course_node, 'field_course_picture', array('settings' => array('image_style' => 'course_header_list_item')));
        //get sure that image style exists
        $uri = $field_view['#items'][0]['uri'];
        $url = image_style_url('course_header_list_item', $uri);

        //$url = parse_url($url_array);
        //        dpm($url);
        //$path = $url['path'];
        $path = $url;
        $header_pic = '<div style="
        background-image:url(' . $path . ');
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover; 
        height:130px;
        ">
        </div>';
        $vars['image'] = $header_pic;
      }


      $vars['title'] = $course_node->title;
      $vars['subtitle'] = render(field_view_field('node', $course_node, 'field_subtitle', array('label'=>'hidden')));
     
      $vars['link'] = url('course/home/' . $course_node->nid);
      $field_view = field_view_field('node', $course_node, 'field_short_description', array('label'=>'hidden'));
      $alter = array(
        'max_length' => 540,
        'ellipsis' => TRUE,
      );
      $trimmed_desc = views_trim_text($alter, render($field_view));

      $vars['description'] = $trimmed_desc;

      $output .= theme('nm_course_list_item', $vars);
    }
  }


  return $output;
}

function section_spaces_main_themen_view() {
  $output = 'themen';

  return $output;
}

function section_spaces_main_partner_view() {
  $output = 'partner';

  return $output;
}