<?php
/**
 * implements   hook_form_alter(&$form, &$form_state, $form_id) {
 * Deaktiviere Student-Profil-Settings
 * @param boolean $form
 * @param type $form_state
 * @param type $form_id
 */
function schullabor_form_alter(&$form, &$form_state, $form_id) {
    if ($form_id == 'user_profile_form') {
        $form['profile_student']['#access'] = false;
    }
}
 

/**
 * implements template_preprocess_page(&$variables) {
 * @param type $variables
 * @param type $hook
 */
function schullabor_preprocess_page(&$variables, $hook) {
    global $user;

    //homescreen für loggedout
    if (!$user->uid && drupal_is_front_page()) {
        drupal_add_css(drupal_get_path('module', 'schullabor') . '/assets/schullabor_home.css');
    }
    
    //setze logo oben
    $variables['logo'] = url(drupal_get_path('module', 'schullabor') . '/assets/images/schullabor-logo.png', array('absolute' => TRUE));
}
 
/**
 * implements hook_init() 
 * wird genutzt, um im Plugin den nav-bar-style zu ändern. 
 * ändert den Config-Wert, ohne die DB zu beeinflussen.
 */
function schullabor_init() {
    global $conf;
    $conf['theme_bootstrap_onlinekurslabor_settings']['bootstrap_navbar_inverse'] = 0;
}
