<?php

/**
 * 
 * todo
 * 
 */
 
/**
 * Implements hook_init().
 */
function linkit_extension_page_build() { 
     
     drupal_add_js(drupal_get_path('module', 'linkit') . '/better-autocomplete/jquery.better-autocomplete.js');
     drupal_add_css(drupal_get_path('module', 'linkit') . '/better-autocomplete/better-autocomplete.css', array('type'=>'file'));
  drupal_add_js(drupal_get_path('module', 'linkit_extension') . '/assets/js/linkit_extension.js');
 
}
  
/**
 * Initializes the site-options and callback
 *
 * @return Array containing module-information
 */
function linkit_extension_menu() {
  $items = array();
  $items['linkit_extension'] = array(
    'title' => 'blub',
    
    'page callback' => 'linkit_extension_page_callback',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM
  );
  return $items;
}
/**
 * returns the rendered form
 *
 * @return Support-Form
 */
function linkit_extension_page_callback() {
    /*ab hier haben wir das problem, dass die js-effekte nur greifen,
wenn wir return machen. damit wird nämlich die ganze seite geladen und
     * die neu hinzugekommenenen html-objekte werden auch verarbeitet. 
     * machen wir echo, wird nur hart html ausgegeben. und das wird nicht verarbeitet.
     */
  return linkit_extension_render();
  echo linkit_extension_render(); //fuer ajax
}


/**
 * renders form and modal-divs
 * @return string
 */
function linkit_extension_render() {
  global $user;

  //just for authenticated users
  if($user->uid > 0){
     $form = drupal_get_form("linkit_extension_getform");
    return drupal_render($form);
    }

  return "";
}


/**
 * Creates the supportz-form and returns it
 *
 * @return Support-form
 *//*
function linkit_extension_getform() {
  global $user;
 
  $form = array();
    
  
    
  $form['kontakt']=array(
      '#markup' => '<p>Some text</p>'
  );
  return $form;
}*/


/**
 * Creates the supportz-form and returns it
 *
 * @return Support-form
 */
function linkit_extension_getform_old() {
    $linkit_profile_name = 'h5p_interactive_content';
    $form['form_settings']['go_to_entity'] = array(
        '#type' => 'textfield',
        '#title' => t('File to load upon success'),
        '#default_value' => !empty($conf['go_to_entity']) ? $conf['go_to_entity'] : '',
        '#id' => 'go_to_entity_field',
    );

    $profile = linkit_profile_load($linkit_profile_name);
dpm($profile);
    // Load the insert plugin for the profile.
    $insert_plugin = linkit_insert_plugin_load('raw_url');#$linkit_profile_name);#$profile->data['insert_plugin']['plugin']);
dpm($insert_plugin);
#dpm( ctools_get_plugins('linkit', 'linkit_insert'));
    // Set the field ID.
    $field_id = 'go_to_entity_field';

    $field_js = array(
        'data' => array(
            'linkit' => array(
                'fields' => array(
                    $field_id => array(
                        'profile' => 'h5p_interactive_content',
                        'insert_plugin' => 'raw_url',#$profile->data['insert_plugin']['plugin'],
                        'url_method' => $profile->data['insert_plugin']['url_method'],
                    ),
                ),
            ),
        ),
        'type' => 'setting',
    );

    // Attach js files and settings Linkit needs.
    $form['form_settings']['go_to_entity']['#attached']['library'][] = array('linkit', 'base');
    $form['form_settings']['go_to_entity']['#attached']['library'][] = array('linkit', 'field');
    $form['form_settings']['go_to_entity']['#attached']['js'][] = $insert_plugin['javascript'];
    $form['form_settings']['go_to_entity']['#attached']['js'][] = $field_js;
dpm($form['form_settings']['go_to_entity']['#attached']['js']);
    $button_text = t('Search');
    $form['form_settings']['go_to_entity']['#field_suffix'] = '<a class="button linkit-field-button linkit-field-' . $field_id . '" href="#">' . $button_text . '</a>';
    return $form;
}
/*
function linkit_extension_form_alter(&$form, &$form_state, $form_id) {
  #  dpm($form);
    if(!in_array($form_id, array('linkit_dashboard_form')))
    {
          $form['linkit_extension'] = linkit_extension_getform();
      dpm($form);
    }

}*/

function linkit_extension_getform()
{  $linkit_profile_name = 'h5p_interactive_content';
    $linkit_insert_pluginname = 'raw_url';
    $element_id = 'go_to_entity_field';
    $element =  array(
        '#type' => 'textfield',
        '#title' => t('Klick auf Suche'),
        '#default_value' => !empty($conf['go_to_entity']) ? $conf['go_to_entity'] : '',
        '#id' => $element_id,
    );;
    
 

  // Load the profile.
  /* @var \LinkitProfile $profile */
  $profile = linkit_profile_load($linkit_profile_name);

  // Load the insert plugin for the profile.
  $insert_plugin = linkit_insert_plugin_load($linkit_insert_pluginname);
  $js_settings = array(
    'helper' => 'field',
    'source' => $element['#id'],
    'profile' =>  $linkit_profile_name,
    'insertPlugin' => $linkit_insert_pluginname,
  );

 

  // Add Linkit dialog button to the element suffix.
  $element['#field_suffix'] = l(empty($instance['settings']['linkit']['button_text']) ? t('Search') : $instance['settings']['linkit']['button_text'], '', array(
    'attributes' => array(
      'class' => array(
        "button",
        "linkit-field-button",
        "linkit-field-{$js_settings['source']}",
      ),
    ),
  ));

  // Attach js files and settings Linkit needs.
  $element['#attached']['library'][] = array('linkit', 'base');
  $element['#attached']['library'][] = array('linkit', 'field');
  $element['#attached']['js'][] = $insert_plugin['javascript'];
  $element['#attached']['js'][] = array(
    'type' => 'setting',
    'data' => array(
      'linkit' => array('fields' => array($js_settings)),
    ),
  );
  #return $element;
  $form =  array('greatform'=> array("element" =>$element));
  $form['greatform']['js'] =
array('#markup'=> "<script src=sites/all/modules/linkit/plugins/linkit_insert/raw_url/raw_url.js>");         
 dpm($form);
 $profile = 
  #linkit_set_active_profile(linkit_profile_load($linkit_profile_name));
 $form =  $form = linkit_dashboard_page(linkit_profile_load($linkit_profile_name));#drupal_get_form('linkit_dashboard_form');
 dpm($form);
return $form;
}