<?php
/**
 * @file
 * section_projects_features.features.og_features_permission.inc
 */

/**
 * Implements hook_og_features_default_permissions().
 */
function section_projects_features_og_features_default_permissions() {
  $permissions = array();

  // Exported og permission: 'node:courses_course:create projects_blog content'
  $permissions['node:courses_course:create projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:create projects_documentation content'
  $permissions['node:courses_course:create projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:create projects_objective content'
  $permissions['node:courses_course:create projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:create projects_proposal content'
  $permissions['node:courses_course:create projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:delete any projects_blog content'
  $permissions['node:courses_course:delete any projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:delete any projects_documentation content'
  $permissions['node:courses_course:delete any projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:delete any projects_objective content'
  $permissions['node:courses_course:delete any projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:delete any projects_proposal content'
  $permissions['node:courses_course:delete any projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:delete own projects_blog content'
  $permissions['node:courses_course:delete own projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:delete own projects_documentation content'
  $permissions['node:courses_course:delete own projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:delete own projects_objective content'
  $permissions['node:courses_course:delete own projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:delete own projects_proposal content'
  $permissions['node:courses_course:delete own projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:update any projects_blog content'
  $permissions['node:courses_course:update any projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:update any projects_documentation content'
  $permissions['node:courses_course:update any projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:update any projects_objective content'
  $permissions['node:courses_course:update any projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:update any projects_proposal content'
  $permissions['node:courses_course:update any projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:update own projects_blog content'
  $permissions['node:courses_course:update own projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:update own projects_documentation content'
  $permissions['node:courses_course:update own projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:update own projects_objective content'
  $permissions['node:courses_course:update own projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:update own projects_proposal content'
  $permissions['node:courses_course:update own projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:create projects_blog content'
  $permissions['node:courses_group:create projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:create projects_documentation content'
  $permissions['node:courses_group:create projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:create projects_objective content'
  $permissions['node:courses_group:create projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:create projects_proposal content'
  $permissions['node:courses_group:create projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:delete any projects_blog content'
  $permissions['node:courses_group:delete any projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:delete any projects_documentation content'
  $permissions['node:courses_group:delete any projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:delete any projects_objective content'
  $permissions['node:courses_group:delete any projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:delete any projects_proposal content'
  $permissions['node:courses_group:delete any projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:delete own projects_blog content'
  $permissions['node:courses_group:delete own projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:delete own projects_documentation content'
  $permissions['node:courses_group:delete own projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:delete own projects_objective content'
  $permissions['node:courses_group:delete own projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:delete own projects_proposal content'
  $permissions['node:courses_group:delete own projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:update any projects_blog content'
  $permissions['node:courses_group:update any projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:update any projects_documentation content'
  $permissions['node:courses_group:update any projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:update any projects_objective content'
  $permissions['node:courses_group:update any projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:update any projects_proposal content'
  $permissions['node:courses_group:update any projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:update own projects_blog content'
  $permissions['node:courses_group:update own projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:update own projects_documentation content'
  $permissions['node:courses_group:update own projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:update own projects_objective content'
  $permissions['node:courses_group:update own projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:update own projects_proposal content'
  $permissions['node:courses_group:update own projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:add user'
  $permissions['node:projects_cooperation_agreement:add user'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:administer group'
  $permissions['node:projects_cooperation_agreement:administer group'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:approve and deny subscription'
  $permissions['node:projects_cooperation_agreement:approve and deny subscription'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create biblio content'
  $permissions['node:projects_cooperation_agreement:create biblio content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create content_chapter content'
  $permissions['node:projects_cooperation_agreement:create content_chapter content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create content_multiple_choice content'
  $permissions['node:projects_cooperation_agreement:create content_multiple_choice content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create content_question_and_answer content'
  $permissions['node:projects_cooperation_agreement:create content_question_and_answer content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create courses_docs content'
  $permissions['node:projects_cooperation_agreement:create courses_docs content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create courses_generic_task content'
  $permissions['node:projects_cooperation_agreement:create courses_generic_task content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create courses_generic_task_solution content'
  $permissions['node:projects_cooperation_agreement:create courses_generic_task_solution content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create courses_group content'
  $permissions['node:projects_cooperation_agreement:create courses_group content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create courses_news content'
  $permissions['node:projects_cooperation_agreement:create courses_news content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create forum content'
  $permissions['node:projects_cooperation_agreement:create forum content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create h5p_content content'
  $permissions['node:projects_cooperation_agreement:create h5p_content content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create nm_stream content'
  $permissions['node:projects_cooperation_agreement:create nm_stream content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create projects_blog content'
  $permissions['node:projects_cooperation_agreement:create projects_blog content'] = array(
    'roles' => array(
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create projects_documentation content'
  $permissions['node:projects_cooperation_agreement:create projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create projects_objective content'
  $permissions['node:projects_cooperation_agreement:create projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create projects_proposal content'
  $permissions['node:projects_cooperation_agreement:create projects_proposal content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any biblio content'
  $permissions['node:projects_cooperation_agreement:delete any biblio content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any content_chapter content'
  $permissions['node:projects_cooperation_agreement:delete any content_chapter content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any content_multiple_choice content'
  $permissions['node:projects_cooperation_agreement:delete any content_multiple_choice content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any content_question_and_answer content'
  $permissions['node:projects_cooperation_agreement:delete any content_question_and_answer content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any courses_docs content'
  $permissions['node:projects_cooperation_agreement:delete any courses_docs content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any courses_generic_task content'
  $permissions['node:projects_cooperation_agreement:delete any courses_generic_task content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any courses_generic_task_solution content'
  $permissions['node:projects_cooperation_agreement:delete any courses_generic_task_solution content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any courses_group content'
  $permissions['node:projects_cooperation_agreement:delete any courses_group content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any courses_news content'
  $permissions['node:projects_cooperation_agreement:delete any courses_news content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any forum content'
  $permissions['node:projects_cooperation_agreement:delete any forum content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any h5p_content content'
  $permissions['node:projects_cooperation_agreement:delete any h5p_content content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any nm_stream content'
  $permissions['node:projects_cooperation_agreement:delete any nm_stream content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any projects_blog content'
  $permissions['node:projects_cooperation_agreement:delete any projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any projects_documentation content'
  $permissions['node:projects_cooperation_agreement:delete any projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any projects_objective content'
  $permissions['node:projects_cooperation_agreement:delete any projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any projects_proposal content'
  $permissions['node:projects_cooperation_agreement:delete any projects_proposal content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own biblio content'
  $permissions['node:projects_cooperation_agreement:delete own biblio content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own content_chapter content'
  $permissions['node:projects_cooperation_agreement:delete own content_chapter content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own content_multiple_choice content'
  $permissions['node:projects_cooperation_agreement:delete own content_multiple_choice content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own content_question_and_answer content'
  $permissions['node:projects_cooperation_agreement:delete own content_question_and_answer content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own courses_docs content'
  $permissions['node:projects_cooperation_agreement:delete own courses_docs content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own courses_generic_task content'
  $permissions['node:projects_cooperation_agreement:delete own courses_generic_task content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own courses_generic_task_solution content'
  $permissions['node:projects_cooperation_agreement:delete own courses_generic_task_solution content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own courses_group content'
  $permissions['node:projects_cooperation_agreement:delete own courses_group content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own courses_news content'
  $permissions['node:projects_cooperation_agreement:delete own courses_news content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own forum content'
  $permissions['node:projects_cooperation_agreement:delete own forum content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own h5p_content content'
  $permissions['node:projects_cooperation_agreement:delete own h5p_content content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own nm_stream content'
  $permissions['node:projects_cooperation_agreement:delete own nm_stream content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own projects_blog content'
  $permissions['node:projects_cooperation_agreement:delete own projects_blog content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own projects_documentation content'
  $permissions['node:projects_cooperation_agreement:delete own projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own projects_objective content'
  $permissions['node:projects_cooperation_agreement:delete own projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own projects_proposal content'
  $permissions['node:projects_cooperation_agreement:delete own projects_proposal content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:edit any master profile'
  $permissions['node:projects_cooperation_agreement:edit any master profile'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:edit any student profile'
  $permissions['node:projects_cooperation_agreement:edit any student profile'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:manage members'
  $permissions['node:projects_cooperation_agreement:manage members'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:manage permissions'
  $permissions['node:projects_cooperation_agreement:manage permissions'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:manage roles'
  $permissions['node:projects_cooperation_agreement:manage roles'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:moderate'
  $permissions['node:projects_cooperation_agreement:moderate'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'forum administrator' => 'forum administrator',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:subscribe'
  $permissions['node:projects_cooperation_agreement:subscribe'] = array(
    'roles' => array(
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:subscribe without approval'
  $permissions['node:projects_cooperation_agreement:subscribe without approval'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:unsubscribe'
  $permissions['node:projects_cooperation_agreement:unsubscribe'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any biblio content'
  $permissions['node:projects_cooperation_agreement:update any biblio content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any content_chapter content'
  $permissions['node:projects_cooperation_agreement:update any content_chapter content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any content_multiple_choice content'
  $permissions['node:projects_cooperation_agreement:update any content_multiple_choice content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any content_question_and_answer content'
  $permissions['node:projects_cooperation_agreement:update any content_question_and_answer content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any courses_docs content'
  $permissions['node:projects_cooperation_agreement:update any courses_docs content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any courses_generic_task content'
  $permissions['node:projects_cooperation_agreement:update any courses_generic_task content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any courses_generic_task_solution content'
  $permissions['node:projects_cooperation_agreement:update any courses_generic_task_solution content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any courses_group content'
  $permissions['node:projects_cooperation_agreement:update any courses_group content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any courses_news content'
  $permissions['node:projects_cooperation_agreement:update any courses_news content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any forum content'
  $permissions['node:projects_cooperation_agreement:update any forum content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any h5p_content content'
  $permissions['node:projects_cooperation_agreement:update any h5p_content content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any nm_stream content'
  $permissions['node:projects_cooperation_agreement:update any nm_stream content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any projects_blog content'
  $permissions['node:projects_cooperation_agreement:update any projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any projects_documentation content'
  $permissions['node:projects_cooperation_agreement:update any projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any projects_objective content'
  $permissions['node:projects_cooperation_agreement:update any projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any projects_proposal content'
  $permissions['node:projects_cooperation_agreement:update any projects_proposal content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update group'
  $permissions['node:projects_cooperation_agreement:update group'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own biblio content'
  $permissions['node:projects_cooperation_agreement:update own biblio content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own content_chapter content'
  $permissions['node:projects_cooperation_agreement:update own content_chapter content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own content_multiple_choice content'
  $permissions['node:projects_cooperation_agreement:update own content_multiple_choice content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own content_question_and_answer content'
  $permissions['node:projects_cooperation_agreement:update own content_question_and_answer content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own courses_docs content'
  $permissions['node:projects_cooperation_agreement:update own courses_docs content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own courses_generic_task content'
  $permissions['node:projects_cooperation_agreement:update own courses_generic_task content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own courses_generic_task_solution content'
  $permissions['node:projects_cooperation_agreement:update own courses_generic_task_solution content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own courses_group content'
  $permissions['node:projects_cooperation_agreement:update own courses_group content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own courses_news content'
  $permissions['node:projects_cooperation_agreement:update own courses_news content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own forum content'
  $permissions['node:projects_cooperation_agreement:update own forum content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own h5p_content content'
  $permissions['node:projects_cooperation_agreement:update own h5p_content content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own nm_stream content'
  $permissions['node:projects_cooperation_agreement:update own nm_stream content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own projects_blog content'
  $permissions['node:projects_cooperation_agreement:update own projects_blog content'] = array(
    'roles' => array(
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own projects_documentation content'
  $permissions['node:projects_cooperation_agreement:update own projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own projects_objective content'
  $permissions['node:projects_cooperation_agreement:update own projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own projects_proposal content'
  $permissions['node:projects_cooperation_agreement:update own projects_proposal content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view any master profile'
  $permissions['node:projects_cooperation_agreement:view any master profile'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view any student profile'
  $permissions['node:projects_cooperation_agreement:view any student profile'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:add user'
  $permissions['node:projects_organization:add user'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:administer group'
  $permissions['node:projects_organization:administer group'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:approve and deny subscription'
  $permissions['node:projects_organization:approve and deny subscription'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create biblio content'
  $permissions['node:projects_organization:create biblio content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create content_chapter content'
  $permissions['node:projects_organization:create content_chapter content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create content_multiple_choice content'
  $permissions['node:projects_organization:create content_multiple_choice content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create content_question_and_answer content'
  $permissions['node:projects_organization:create content_question_and_answer content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create courses_docs content'
  $permissions['node:projects_organization:create courses_docs content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create courses_generic_task content'
  $permissions['node:projects_organization:create courses_generic_task content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create courses_generic_task_solution content'
  $permissions['node:projects_organization:create courses_generic_task_solution content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create courses_group content'
  $permissions['node:projects_organization:create courses_group content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create courses_news content'
  $permissions['node:projects_organization:create courses_news content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create forum content'
  $permissions['node:projects_organization:create forum content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create h5p_content content'
  $permissions['node:projects_organization:create h5p_content content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create nm_stream content'
  $permissions['node:projects_organization:create nm_stream content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create projects_blog content'
  $permissions['node:projects_organization:create projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:create projects_documentation content'
  $permissions['node:projects_organization:create projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:create projects_objective content'
  $permissions['node:projects_organization:create projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:create projects_proposal content'
  $permissions['node:projects_organization:create projects_proposal content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any biblio content'
  $permissions['node:projects_organization:delete any biblio content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any content_chapter content'
  $permissions['node:projects_organization:delete any content_chapter content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any content_multiple_choice content'
  $permissions['node:projects_organization:delete any content_multiple_choice content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any content_question_and_answer content'
  $permissions['node:projects_organization:delete any content_question_and_answer content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any courses_docs content'
  $permissions['node:projects_organization:delete any courses_docs content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any courses_generic_task content'
  $permissions['node:projects_organization:delete any courses_generic_task content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any courses_generic_task_solution content'
  $permissions['node:projects_organization:delete any courses_generic_task_solution content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any courses_group content'
  $permissions['node:projects_organization:delete any courses_group content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any courses_news content'
  $permissions['node:projects_organization:delete any courses_news content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any forum content'
  $permissions['node:projects_organization:delete any forum content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any h5p_content content'
  $permissions['node:projects_organization:delete any h5p_content content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any nm_stream content'
  $permissions['node:projects_organization:delete any nm_stream content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:delete any projects_blog content'
  $permissions['node:projects_organization:delete any projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:delete any projects_documentation content'
  $permissions['node:projects_organization:delete any projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:delete any projects_objective content'
  $permissions['node:projects_organization:delete any projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:delete any projects_proposal content'
  $permissions['node:projects_organization:delete any projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:delete own biblio content'
  $permissions['node:projects_organization:delete own biblio content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own content_chapter content'
  $permissions['node:projects_organization:delete own content_chapter content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own content_multiple_choice content'
  $permissions['node:projects_organization:delete own content_multiple_choice content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own content_question_and_answer content'
  $permissions['node:projects_organization:delete own content_question_and_answer content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own courses_docs content'
  $permissions['node:projects_organization:delete own courses_docs content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own courses_generic_task content'
  $permissions['node:projects_organization:delete own courses_generic_task content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own courses_generic_task_solution content'
  $permissions['node:projects_organization:delete own courses_generic_task_solution content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own courses_group content'
  $permissions['node:projects_organization:delete own courses_group content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own courses_news content'
  $permissions['node:projects_organization:delete own courses_news content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own forum content'
  $permissions['node:projects_organization:delete own forum content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own h5p_content content'
  $permissions['node:projects_organization:delete own h5p_content content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own nm_stream content'
  $permissions['node:projects_organization:delete own nm_stream content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:delete own projects_blog content'
  $permissions['node:projects_organization:delete own projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:delete own projects_documentation content'
  $permissions['node:projects_organization:delete own projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:delete own projects_objective content'
  $permissions['node:projects_organization:delete own projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:delete own projects_proposal content'
  $permissions['node:projects_organization:delete own projects_proposal content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:edit any master profile'
  $permissions['node:projects_organization:edit any master profile'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:edit any student profile'
  $permissions['node:projects_organization:edit any student profile'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:manage members'
  $permissions['node:projects_organization:manage members'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:manage permissions'
  $permissions['node:projects_organization:manage permissions'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:manage roles'
  $permissions['node:projects_organization:manage roles'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:moderate'
  $permissions['node:projects_organization:moderate'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'forum administrator' => 'forum administrator',
    ),
  );

  // Exported og permission: 'node:projects_organization:subscribe'
  $permissions['node:projects_organization:subscribe'] = array(
    'roles' => array(
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:subscribe without approval'
  $permissions['node:projects_organization:subscribe without approval'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:unsubscribe'
  $permissions['node:projects_organization:unsubscribe'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any biblio content'
  $permissions['node:projects_organization:update any biblio content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any content_chapter content'
  $permissions['node:projects_organization:update any content_chapter content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any content_multiple_choice content'
  $permissions['node:projects_organization:update any content_multiple_choice content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any content_question_and_answer content'
  $permissions['node:projects_organization:update any content_question_and_answer content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any courses_docs content'
  $permissions['node:projects_organization:update any courses_docs content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any courses_generic_task content'
  $permissions['node:projects_organization:update any courses_generic_task content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any courses_generic_task_solution content'
  $permissions['node:projects_organization:update any courses_generic_task_solution content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any courses_group content'
  $permissions['node:projects_organization:update any courses_group content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any courses_news content'
  $permissions['node:projects_organization:update any courses_news content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any forum content'
  $permissions['node:projects_organization:update any forum content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any h5p_content content'
  $permissions['node:projects_organization:update any h5p_content content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any nm_stream content'
  $permissions['node:projects_organization:update any nm_stream content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update any projects_blog content'
  $permissions['node:projects_organization:update any projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update any projects_documentation content'
  $permissions['node:projects_organization:update any projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update any projects_objective content'
  $permissions['node:projects_organization:update any projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update any projects_proposal content'
  $permissions['node:projects_organization:update any projects_proposal content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update group'
  $permissions['node:projects_organization:update group'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own biblio content'
  $permissions['node:projects_organization:update own biblio content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own content_chapter content'
  $permissions['node:projects_organization:update own content_chapter content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own content_multiple_choice content'
  $permissions['node:projects_organization:update own content_multiple_choice content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own content_question_and_answer content'
  $permissions['node:projects_organization:update own content_question_and_answer content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own courses_docs content'
  $permissions['node:projects_organization:update own courses_docs content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own courses_generic_task content'
  $permissions['node:projects_organization:update own courses_generic_task content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own courses_generic_task_solution content'
  $permissions['node:projects_organization:update own courses_generic_task_solution content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own courses_group content'
  $permissions['node:projects_organization:update own courses_group content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own courses_news content'
  $permissions['node:projects_organization:update own courses_news content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own forum content'
  $permissions['node:projects_organization:update own forum content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own h5p_content content'
  $permissions['node:projects_organization:update own h5p_content content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own nm_stream content'
  $permissions['node:projects_organization:update own nm_stream content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update own projects_blog content'
  $permissions['node:projects_organization:update own projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update own projects_documentation content'
  $permissions['node:projects_organization:update own projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update own projects_objective content'
  $permissions['node:projects_organization:update own projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update own projects_proposal content'
  $permissions['node:projects_organization:update own projects_proposal content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view any master profile'
  $permissions['node:projects_organization:view any master profile'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view any student profile'
  $permissions['node:projects_organization:view any student profile'] = array(
    'roles' => array(),
  );

  return $permissions;
}
