<?php
/**
 * @file
 * section_projects_features.features.og_features_permission.inc
 */

/**
 * Implements hook_og_features_default_permissions().
 */
function section_projects_features_og_features_default_permissions() {
  $permissions = array();

  // Exported og permission: 'node:courses_course:create projects_blog content'
  $permissions['node:courses_course:create projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:create projects_documentation content'
  $permissions['node:courses_course:create projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:create projects_objective content'
  $permissions['node:courses_course:create projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:create projects_proposal content'
  $permissions['node:courses_course:create projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:delete any projects_blog content'
  $permissions['node:courses_course:delete any projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:delete any projects_documentation content'
  $permissions['node:courses_course:delete any projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:delete any projects_objective content'
  $permissions['node:courses_course:delete any projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:delete any projects_proposal content'
  $permissions['node:courses_course:delete any projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:delete own projects_blog content'
  $permissions['node:courses_course:delete own projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:delete own projects_documentation content'
  $permissions['node:courses_course:delete own projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:delete own projects_objective content'
  $permissions['node:courses_course:delete own projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:delete own projects_proposal content'
  $permissions['node:courses_course:delete own projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:update any projects_blog content'
  $permissions['node:courses_course:update any projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:update any projects_documentation content'
  $permissions['node:courses_course:update any projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:update any projects_objective content'
  $permissions['node:courses_course:update any projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:update any projects_proposal content'
  $permissions['node:courses_course:update any projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:update field_projects_blog_attachments field'
  $permissions['node:courses_course:update field_projects_blog_attachments field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:update own projects_blog content'
  $permissions['node:courses_course:update own projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:update own projects_documentation content'
  $permissions['node:courses_course:update own projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:update own projects_objective content'
  $permissions['node:courses_course:update own projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:update own projects_proposal content'
  $permissions['node:courses_course:update own projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_course:view field_projects_blog_attachments field'
  $permissions['node:courses_course:view field_projects_blog_attachments field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:create projects_blog content'
  $permissions['node:courses_group:create projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:create projects_documentation content'
  $permissions['node:courses_group:create projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:create projects_objective content'
  $permissions['node:courses_group:create projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:create projects_proposal content'
  $permissions['node:courses_group:create projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:delete any projects_blog content'
  $permissions['node:courses_group:delete any projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:delete any projects_documentation content'
  $permissions['node:courses_group:delete any projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:delete any projects_objective content'
  $permissions['node:courses_group:delete any projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:delete any projects_proposal content'
  $permissions['node:courses_group:delete any projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:delete own projects_blog content'
  $permissions['node:courses_group:delete own projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:delete own projects_documentation content'
  $permissions['node:courses_group:delete own projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:delete own projects_objective content'
  $permissions['node:courses_group:delete own projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:delete own projects_proposal content'
  $permissions['node:courses_group:delete own projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:update any projects_blog content'
  $permissions['node:courses_group:update any projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:update any projects_documentation content'
  $permissions['node:courses_group:update any projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:update any projects_objective content'
  $permissions['node:courses_group:update any projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:update any projects_proposal content'
  $permissions['node:courses_group:update any projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:update field_projects_blog_attachments field'
  $permissions['node:courses_group:update field_projects_blog_attachments field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:update own projects_blog content'
  $permissions['node:courses_group:update own projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:update own projects_documentation content'
  $permissions['node:courses_group:update own projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:update own projects_objective content'
  $permissions['node:courses_group:update own projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:update own projects_proposal content'
  $permissions['node:courses_group:update own projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:courses_group:view field_projects_blog_attachments field'
  $permissions['node:courses_group:view field_projects_blog_attachments field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:add user'
  $permissions['node:projects_cooperation_agreement:add user'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:administer group'
  $permissions['node:projects_cooperation_agreement:administer group'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:approve and deny subscription'
  $permissions['node:projects_cooperation_agreement:approve and deny subscription'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create biblio content'
  $permissions['node:projects_cooperation_agreement:create biblio content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create content_chapter content'
  $permissions['node:projects_cooperation_agreement:create content_chapter content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create content_multiple_choice content'
  $permissions['node:projects_cooperation_agreement:create content_multiple_choice content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create content_question_and_answer content'
  $permissions['node:projects_cooperation_agreement:create content_question_and_answer content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create courses_docs content'
  $permissions['node:projects_cooperation_agreement:create courses_docs content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create courses_generic_task content'
  $permissions['node:projects_cooperation_agreement:create courses_generic_task content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create courses_generic_task_solution content'
  $permissions['node:projects_cooperation_agreement:create courses_generic_task_solution content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create courses_group content'
  $permissions['node:projects_cooperation_agreement:create courses_group content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create courses_news content'
  $permissions['node:projects_cooperation_agreement:create courses_news content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create forum content'
  $permissions['node:projects_cooperation_agreement:create forum content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create h5p_content content'
  $permissions['node:projects_cooperation_agreement:create h5p_content content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create nm_stream content'
  $permissions['node:projects_cooperation_agreement:create nm_stream content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create projects_blog content'
  $permissions['node:projects_cooperation_agreement:create projects_blog content'] = array(
    'roles' => array(
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create projects_documentation content'
  $permissions['node:projects_cooperation_agreement:create projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create projects_objective content'
  $permissions['node:projects_cooperation_agreement:create projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create projects_proposal content'
  $permissions['node:projects_cooperation_agreement:create projects_proposal content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:create webform content'
  $permissions['node:projects_cooperation_agreement:create webform content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any biblio content'
  $permissions['node:projects_cooperation_agreement:delete any biblio content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any content_chapter content'
  $permissions['node:projects_cooperation_agreement:delete any content_chapter content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any content_multiple_choice content'
  $permissions['node:projects_cooperation_agreement:delete any content_multiple_choice content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any content_question_and_answer content'
  $permissions['node:projects_cooperation_agreement:delete any content_question_and_answer content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any courses_docs content'
  $permissions['node:projects_cooperation_agreement:delete any courses_docs content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any courses_generic_task content'
  $permissions['node:projects_cooperation_agreement:delete any courses_generic_task content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any courses_generic_task_solution content'
  $permissions['node:projects_cooperation_agreement:delete any courses_generic_task_solution content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any courses_group content'
  $permissions['node:projects_cooperation_agreement:delete any courses_group content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any courses_news content'
  $permissions['node:projects_cooperation_agreement:delete any courses_news content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any forum content'
  $permissions['node:projects_cooperation_agreement:delete any forum content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any h5p_content content'
  $permissions['node:projects_cooperation_agreement:delete any h5p_content content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any nm_stream content'
  $permissions['node:projects_cooperation_agreement:delete any nm_stream content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any projects_blog content'
  $permissions['node:projects_cooperation_agreement:delete any projects_blog content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any projects_documentation content'
  $permissions['node:projects_cooperation_agreement:delete any projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any projects_objective content'
  $permissions['node:projects_cooperation_agreement:delete any projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any projects_proposal content'
  $permissions['node:projects_cooperation_agreement:delete any projects_proposal content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete any webform content'
  $permissions['node:projects_cooperation_agreement:delete any webform content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own biblio content'
  $permissions['node:projects_cooperation_agreement:delete own biblio content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own content_chapter content'
  $permissions['node:projects_cooperation_agreement:delete own content_chapter content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own content_multiple_choice content'
  $permissions['node:projects_cooperation_agreement:delete own content_multiple_choice content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own content_question_and_answer content'
  $permissions['node:projects_cooperation_agreement:delete own content_question_and_answer content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own courses_docs content'
  $permissions['node:projects_cooperation_agreement:delete own courses_docs content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own courses_generic_task content'
  $permissions['node:projects_cooperation_agreement:delete own courses_generic_task content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own courses_generic_task_solution content'
  $permissions['node:projects_cooperation_agreement:delete own courses_generic_task_solution content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own courses_group content'
  $permissions['node:projects_cooperation_agreement:delete own courses_group content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own courses_news content'
  $permissions['node:projects_cooperation_agreement:delete own courses_news content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own forum content'
  $permissions['node:projects_cooperation_agreement:delete own forum content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own h5p_content content'
  $permissions['node:projects_cooperation_agreement:delete own h5p_content content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own nm_stream content'
  $permissions['node:projects_cooperation_agreement:delete own nm_stream content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own projects_blog content'
  $permissions['node:projects_cooperation_agreement:delete own projects_blog content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own projects_documentation content'
  $permissions['node:projects_cooperation_agreement:delete own projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own projects_objective content'
  $permissions['node:projects_cooperation_agreement:delete own projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own projects_proposal content'
  $permissions['node:projects_cooperation_agreement:delete own projects_proposal content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:delete own webform content'
  $permissions['node:projects_cooperation_agreement:delete own webform content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:edit any master profile'
  $permissions['node:projects_cooperation_agreement:edit any master profile'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:edit any student profile'
  $permissions['node:projects_cooperation_agreement:edit any student profile'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:manage members'
  $permissions['node:projects_cooperation_agreement:manage members'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:manage permissions'
  $permissions['node:projects_cooperation_agreement:manage permissions'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:manage roles'
  $permissions['node:projects_cooperation_agreement:manage roles'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:moderate'
  $permissions['node:projects_cooperation_agreement:moderate'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'forum administrator' => 'forum administrator',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:subscribe'
  $permissions['node:projects_cooperation_agreement:subscribe'] = array(
    'roles' => array(
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:subscribe without approval'
  $permissions['node:projects_cooperation_agreement:subscribe without approval'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:unsubscribe'
  $permissions['node:projects_cooperation_agreement:unsubscribe'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any biblio content'
  $permissions['node:projects_cooperation_agreement:update any biblio content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any content_chapter content'
  $permissions['node:projects_cooperation_agreement:update any content_chapter content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any content_multiple_choice content'
  $permissions['node:projects_cooperation_agreement:update any content_multiple_choice content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any content_question_and_answer content'
  $permissions['node:projects_cooperation_agreement:update any content_question_and_answer content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any courses_docs content'
  $permissions['node:projects_cooperation_agreement:update any courses_docs content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any courses_generic_task content'
  $permissions['node:projects_cooperation_agreement:update any courses_generic_task content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any courses_generic_task_solution content'
  $permissions['node:projects_cooperation_agreement:update any courses_generic_task_solution content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any courses_group content'
  $permissions['node:projects_cooperation_agreement:update any courses_group content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any courses_news content'
  $permissions['node:projects_cooperation_agreement:update any courses_news content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any forum content'
  $permissions['node:projects_cooperation_agreement:update any forum content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any h5p_content content'
  $permissions['node:projects_cooperation_agreement:update any h5p_content content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any nm_stream content'
  $permissions['node:projects_cooperation_agreement:update any nm_stream content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any projects_blog content'
  $permissions['node:projects_cooperation_agreement:update any projects_blog content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any projects_documentation content'
  $permissions['node:projects_cooperation_agreement:update any projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any projects_objective content'
  $permissions['node:projects_cooperation_agreement:update any projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any projects_proposal content'
  $permissions['node:projects_cooperation_agreement:update any projects_proposal content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update any webform content'
  $permissions['node:projects_cooperation_agreement:update any webform content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update body field'
  $permissions['node:projects_cooperation_agreement:update body field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update comment_body field'
  $permissions['node:projects_cooperation_agreement:update comment_body field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_access_features field'
  $permissions['node:projects_cooperation_agreement:update field_access_features field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_answer field'
  $permissions['node:projects_cooperation_agreement:update field_answer field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_attachments field'
  $permissions['node:projects_cooperation_agreement:update field_attachments field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_blog_type field'
  $permissions['node:projects_cooperation_agreement:update field_blog_type field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_ca_cooperation_rules field'
  $permissions['node:projects_cooperation_agreement:update field_ca_cooperation_rules field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_ca_course_group_ref field'
  $permissions['node:projects_cooperation_agreement:update field_ca_course_group_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_ca_expectation_academy field'
  $permissions['node:projects_cooperation_agreement:update field_ca_expectation_academy field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_ca_expectation_po field'
  $permissions['node:projects_cooperation_agreement:update field_ca_expectation_po field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_ca_instructors_role field'
  $permissions['node:projects_cooperation_agreement:update field_ca_instructors_role field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_ca_partners_role field'
  $permissions['node:projects_cooperation_agreement:update field_ca_partners_role field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_ca_proposal_ref field'
  $permissions['node:projects_cooperation_agreement:update field_ca_proposal_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_ca_ref field'
  $permissions['node:projects_cooperation_agreement:update field_ca_ref field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_ca_result field'
  $permissions['node:projects_cooperation_agreement:update field_ca_result field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_ca_student_refs field'
  $permissions['node:projects_cooperation_agreement:update field_ca_student_refs field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_ca_students_role field'
  $permissions['node:projects_cooperation_agreement:update field_ca_students_role field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_ca_timespan field'
  $permissions['node:projects_cooperation_agreement:update field_ca_timespan field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_chapter_text field'
  $permissions['node:projects_cooperation_agreement:update field_chapter_text field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_collaborative_features field'
  $permissions['node:projects_cooperation_agreement:update field_collaborative_features field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_course_docs field'
  $permissions['node:projects_cooperation_agreement:update field_course_docs field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_course_group_proposal field'
  $permissions['node:projects_cooperation_agreement:update field_course_group_proposal field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_course_header field'
  $permissions['node:projects_cooperation_agreement:update field_course_header field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_course_picture field'
  $permissions['node:projects_cooperation_agreement:update field_course_picture field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_course_proposals field'
  $permissions['node:projects_cooperation_agreement:update field_course_proposals field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_courses_ref field'
  $permissions['node:projects_cooperation_agreement:update field_courses_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_domain_demo_ref field'
  $permissions['node:projects_cooperation_agreement:update field_domain_demo_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_domain_description field'
  $permissions['node:projects_cooperation_agreement:update field_domain_description field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_domain_picture field'
  $permissions['node:projects_cooperation_agreement:update field_domain_picture field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_domain_ref field'
  $permissions['node:projects_cooperation_agreement:update field_domain_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_domains_ref field'
  $permissions['node:projects_cooperation_agreement:update field_domains_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_field_courses_sponsors field'
  $permissions['node:projects_cooperation_agreement:update field_field_courses_sponsors field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_field_po_contact_person field'
  $permissions['node:projects_cooperation_agreement:update field_field_po_contact_person field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_file_image_alt_text field'
  $permissions['node:projects_cooperation_agreement:update field_file_image_alt_text field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_file_image_title_text field'
  $permissions['node:projects_cooperation_agreement:update field_file_image_title_text field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_generic_solution_entry field'
  $permissions['node:projects_cooperation_agreement:update field_generic_solution_entry field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_generic_task field'
  $permissions['node:projects_cooperation_agreement:update field_generic_task field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_generic_task_assessment field'
  $permissions['node:projects_cooperation_agreement:update field_generic_task_assessment field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_generic_task_entry field'
  $permissions['node:projects_cooperation_agreement:update field_generic_task_entry field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_long_description field'
  $permissions['node:projects_cooperation_agreement:update field_long_description field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_mc_solution field'
  $permissions['node:projects_cooperation_agreement:update field_mc_solution field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_mc_task field'
  $permissions['node:projects_cooperation_agreement:update field_mc_task field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_nm_attachments field'
  $permissions['node:projects_cooperation_agreement:update field_nm_attachments field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_nm_privacy field'
  $permissions['node:projects_cooperation_agreement:update field_nm_privacy field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_objective_matching field'
  $permissions['node:projects_cooperation_agreement:update field_objective_matching field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_objective_motivation field'
  $permissions['node:projects_cooperation_agreement:update field_objective_motivation field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_objective_task field'
  $permissions['node:projects_cooperation_agreement:update field_objective_task field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_operational_area field'
  $permissions['node:projects_cooperation_agreement:update field_operational_area field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_partner_organization_ref field'
  $permissions['node:projects_cooperation_agreement:update field_partner_organization_ref field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_po_contact field'
  $permissions['node:projects_cooperation_agreement:update field_po_contact field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_po_header field'
  $permissions['node:projects_cooperation_agreement:update field_po_header field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_po_logo field'
  $permissions['node:projects_cooperation_agreement:update field_po_logo field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_po_short_description field'
  $permissions['node:projects_cooperation_agreement:update field_po_short_description field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_projects_blog_attachments field'
  $permissions['node:projects_cooperation_agreement:update field_projects_blog_attachments field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_proposal_contact field'
  $permissions['node:projects_cooperation_agreement:update field_proposal_contact field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_proposal_expectation field'
  $permissions['node:projects_cooperation_agreement:update field_proposal_expectation field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_proposal_partners_role field'
  $permissions['node:projects_cooperation_agreement:update field_proposal_partners_role field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_proposal_result field'
  $permissions['node:projects_cooperation_agreement:update field_proposal_result field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_proposal_status field'
  $permissions['node:projects_cooperation_agreement:update field_proposal_status field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_proposal_students_role field'
  $permissions['node:projects_cooperation_agreement:update field_proposal_students_role field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_proposal_task_area field'
  $permissions['node:projects_cooperation_agreement:update field_proposal_task_area field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_proposal_timespan field'
  $permissions['node:projects_cooperation_agreement:update field_proposal_timespan field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_qaa_answer field'
  $permissions['node:projects_cooperation_agreement:update field_qaa_answer field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_qaa_question field'
  $permissions['node:projects_cooperation_agreement:update field_qaa_question field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_seal field'
  $permissions['node:projects_cooperation_agreement:update field_seal field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_semester field'
  $permissions['node:projects_cooperation_agreement:update field_semester field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_short_description field'
  $permissions['node:projects_cooperation_agreement:update field_short_description field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_space_header field'
  $permissions['node:projects_cooperation_agreement:update field_space_header field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_space_home field'
  $permissions['node:projects_cooperation_agreement:update field_space_home field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_subtitle field'
  $permissions['node:projects_cooperation_agreement:update field_subtitle field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_tableofcontents field'
  $permissions['node:projects_cooperation_agreement:update field_tableofcontents field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_task_area field'
  $permissions['node:projects_cooperation_agreement:update field_task_area field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_task_handling_period field'
  $permissions['node:projects_cooperation_agreement:update field_task_handling_period field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_task_type field'
  $permissions['node:projects_cooperation_agreement:update field_task_type field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_time_span field'
  $permissions['node:projects_cooperation_agreement:update field_time_span field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_vhb_lvnr field'
  $permissions['node:projects_cooperation_agreement:update field_vhb_lvnr field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update field_workload field'
  $permissions['node:projects_cooperation_agreement:update field_workload field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update group'
  $permissions['node:projects_cooperation_agreement:update group'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update group_content_access field'
  $permissions['node:projects_cooperation_agreement:update group_content_access field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update group_group field'
  $permissions['node:projects_cooperation_agreement:update group_group field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update og_group_ref field'
  $permissions['node:projects_cooperation_agreement:update og_group_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update og_user_node field'
  $permissions['node:projects_cooperation_agreement:update og_user_node field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own biblio content'
  $permissions['node:projects_cooperation_agreement:update own biblio content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own content_chapter content'
  $permissions['node:projects_cooperation_agreement:update own content_chapter content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own content_multiple_choice content'
  $permissions['node:projects_cooperation_agreement:update own content_multiple_choice content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own content_question_and_answer content'
  $permissions['node:projects_cooperation_agreement:update own content_question_and_answer content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own courses_docs content'
  $permissions['node:projects_cooperation_agreement:update own courses_docs content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own courses_generic_task content'
  $permissions['node:projects_cooperation_agreement:update own courses_generic_task content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own courses_generic_task_solution content'
  $permissions['node:projects_cooperation_agreement:update own courses_generic_task_solution content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own courses_group content'
  $permissions['node:projects_cooperation_agreement:update own courses_group content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own courses_news content'
  $permissions['node:projects_cooperation_agreement:update own courses_news content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own forum content'
  $permissions['node:projects_cooperation_agreement:update own forum content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own h5p_content content'
  $permissions['node:projects_cooperation_agreement:update own h5p_content content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own nm_stream content'
  $permissions['node:projects_cooperation_agreement:update own nm_stream content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own projects_blog content'
  $permissions['node:projects_cooperation_agreement:update own projects_blog content'] = array(
    'roles' => array(
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own projects_documentation content'
  $permissions['node:projects_cooperation_agreement:update own projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own projects_objective content'
  $permissions['node:projects_cooperation_agreement:update own projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own projects_proposal content'
  $permissions['node:projects_cooperation_agreement:update own projects_proposal content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update own webform content'
  $permissions['node:projects_cooperation_agreement:update own webform content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:update taxonomy_forums field'
  $permissions['node:projects_cooperation_agreement:update taxonomy_forums field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view any master profile'
  $permissions['node:projects_cooperation_agreement:view any master profile'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view any student profile'
  $permissions['node:projects_cooperation_agreement:view any student profile'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view body field'
  $permissions['node:projects_cooperation_agreement:view body field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view comment_body field'
  $permissions['node:projects_cooperation_agreement:view comment_body field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_access_features field'
  $permissions['node:projects_cooperation_agreement:view field_access_features field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_answer field'
  $permissions['node:projects_cooperation_agreement:view field_answer field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_attachments field'
  $permissions['node:projects_cooperation_agreement:view field_attachments field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_blog_type field'
  $permissions['node:projects_cooperation_agreement:view field_blog_type field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_ca_cooperation_rules field'
  $permissions['node:projects_cooperation_agreement:view field_ca_cooperation_rules field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_ca_course_group_ref field'
  $permissions['node:projects_cooperation_agreement:view field_ca_course_group_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_ca_expectation_academy field'
  $permissions['node:projects_cooperation_agreement:view field_ca_expectation_academy field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_ca_expectation_po field'
  $permissions['node:projects_cooperation_agreement:view field_ca_expectation_po field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_ca_instructors_role field'
  $permissions['node:projects_cooperation_agreement:view field_ca_instructors_role field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_ca_partners_role field'
  $permissions['node:projects_cooperation_agreement:view field_ca_partners_role field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_ca_proposal_ref field'
  $permissions['node:projects_cooperation_agreement:view field_ca_proposal_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_ca_ref field'
  $permissions['node:projects_cooperation_agreement:view field_ca_ref field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_ca_result field'
  $permissions['node:projects_cooperation_agreement:view field_ca_result field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_ca_student_refs field'
  $permissions['node:projects_cooperation_agreement:view field_ca_student_refs field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_ca_students_role field'
  $permissions['node:projects_cooperation_agreement:view field_ca_students_role field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_ca_timespan field'
  $permissions['node:projects_cooperation_agreement:view field_ca_timespan field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_chapter_text field'
  $permissions['node:projects_cooperation_agreement:view field_chapter_text field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_collaborative_features field'
  $permissions['node:projects_cooperation_agreement:view field_collaborative_features field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_course_docs field'
  $permissions['node:projects_cooperation_agreement:view field_course_docs field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_course_group_proposal field'
  $permissions['node:projects_cooperation_agreement:view field_course_group_proposal field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_course_header field'
  $permissions['node:projects_cooperation_agreement:view field_course_header field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_course_picture field'
  $permissions['node:projects_cooperation_agreement:view field_course_picture field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_course_proposals field'
  $permissions['node:projects_cooperation_agreement:view field_course_proposals field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_courses_ref field'
  $permissions['node:projects_cooperation_agreement:view field_courses_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_domain_demo_ref field'
  $permissions['node:projects_cooperation_agreement:view field_domain_demo_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_domain_description field'
  $permissions['node:projects_cooperation_agreement:view field_domain_description field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_domain_picture field'
  $permissions['node:projects_cooperation_agreement:view field_domain_picture field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_domain_ref field'
  $permissions['node:projects_cooperation_agreement:view field_domain_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_domains_ref field'
  $permissions['node:projects_cooperation_agreement:view field_domains_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_field_courses_sponsors field'
  $permissions['node:projects_cooperation_agreement:view field_field_courses_sponsors field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_field_po_contact_person field'
  $permissions['node:projects_cooperation_agreement:view field_field_po_contact_person field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_file_image_alt_text field'
  $permissions['node:projects_cooperation_agreement:view field_file_image_alt_text field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_file_image_title_text field'
  $permissions['node:projects_cooperation_agreement:view field_file_image_title_text field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_generic_solution_entry field'
  $permissions['node:projects_cooperation_agreement:view field_generic_solution_entry field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_generic_task field'
  $permissions['node:projects_cooperation_agreement:view field_generic_task field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_generic_task_assessment field'
  $permissions['node:projects_cooperation_agreement:view field_generic_task_assessment field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_generic_task_entry field'
  $permissions['node:projects_cooperation_agreement:view field_generic_task_entry field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_long_description field'
  $permissions['node:projects_cooperation_agreement:view field_long_description field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_mc_solution field'
  $permissions['node:projects_cooperation_agreement:view field_mc_solution field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_mc_task field'
  $permissions['node:projects_cooperation_agreement:view field_mc_task field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_nm_attachments field'
  $permissions['node:projects_cooperation_agreement:view field_nm_attachments field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_nm_privacy field'
  $permissions['node:projects_cooperation_agreement:view field_nm_privacy field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_objective_matching field'
  $permissions['node:projects_cooperation_agreement:view field_objective_matching field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_objective_motivation field'
  $permissions['node:projects_cooperation_agreement:view field_objective_motivation field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_objective_task field'
  $permissions['node:projects_cooperation_agreement:view field_objective_task field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_operational_area field'
  $permissions['node:projects_cooperation_agreement:view field_operational_area field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_partner_organization_ref field'
  $permissions['node:projects_cooperation_agreement:view field_partner_organization_ref field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_po_contact field'
  $permissions['node:projects_cooperation_agreement:view field_po_contact field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_po_header field'
  $permissions['node:projects_cooperation_agreement:view field_po_header field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_po_logo field'
  $permissions['node:projects_cooperation_agreement:view field_po_logo field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_po_short_description field'
  $permissions['node:projects_cooperation_agreement:view field_po_short_description field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_projects_blog_attachments field'
  $permissions['node:projects_cooperation_agreement:view field_projects_blog_attachments field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_proposal_contact field'
  $permissions['node:projects_cooperation_agreement:view field_proposal_contact field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_proposal_expectation field'
  $permissions['node:projects_cooperation_agreement:view field_proposal_expectation field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_proposal_partners_role field'
  $permissions['node:projects_cooperation_agreement:view field_proposal_partners_role field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_proposal_result field'
  $permissions['node:projects_cooperation_agreement:view field_proposal_result field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_proposal_status field'
  $permissions['node:projects_cooperation_agreement:view field_proposal_status field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_proposal_students_role field'
  $permissions['node:projects_cooperation_agreement:view field_proposal_students_role field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_proposal_task_area field'
  $permissions['node:projects_cooperation_agreement:view field_proposal_task_area field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_proposal_timespan field'
  $permissions['node:projects_cooperation_agreement:view field_proposal_timespan field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_qaa_answer field'
  $permissions['node:projects_cooperation_agreement:view field_qaa_answer field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_qaa_question field'
  $permissions['node:projects_cooperation_agreement:view field_qaa_question field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_seal field'
  $permissions['node:projects_cooperation_agreement:view field_seal field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_semester field'
  $permissions['node:projects_cooperation_agreement:view field_semester field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_short_description field'
  $permissions['node:projects_cooperation_agreement:view field_short_description field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_space_header field'
  $permissions['node:projects_cooperation_agreement:view field_space_header field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_space_home field'
  $permissions['node:projects_cooperation_agreement:view field_space_home field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_subtitle field'
  $permissions['node:projects_cooperation_agreement:view field_subtitle field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_tableofcontents field'
  $permissions['node:projects_cooperation_agreement:view field_tableofcontents field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_task_area field'
  $permissions['node:projects_cooperation_agreement:view field_task_area field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_task_handling_period field'
  $permissions['node:projects_cooperation_agreement:view field_task_handling_period field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_task_type field'
  $permissions['node:projects_cooperation_agreement:view field_task_type field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_time_span field'
  $permissions['node:projects_cooperation_agreement:view field_time_span field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_vhb_lvnr field'
  $permissions['node:projects_cooperation_agreement:view field_vhb_lvnr field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view field_workload field'
  $permissions['node:projects_cooperation_agreement:view field_workload field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view group_content_access field'
  $permissions['node:projects_cooperation_agreement:view group_content_access field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view group_group field'
  $permissions['node:projects_cooperation_agreement:view group_group field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view og_group_ref field'
  $permissions['node:projects_cooperation_agreement:view og_group_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view og_user_node field'
  $permissions['node:projects_cooperation_agreement:view og_user_node field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_cooperation_agreement:view taxonomy_forums field'
  $permissions['node:projects_cooperation_agreement:view taxonomy_forums field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:add user'
  $permissions['node:projects_organization:add user'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:administer group'
  $permissions['node:projects_organization:administer group'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:approve and deny subscription'
  $permissions['node:projects_organization:approve and deny subscription'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create biblio content'
  $permissions['node:projects_organization:create biblio content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create content_chapter content'
  $permissions['node:projects_organization:create content_chapter content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create content_multiple_choice content'
  $permissions['node:projects_organization:create content_multiple_choice content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create content_question_and_answer content'
  $permissions['node:projects_organization:create content_question_and_answer content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create courses_docs content'
  $permissions['node:projects_organization:create courses_docs content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create courses_generic_task content'
  $permissions['node:projects_organization:create courses_generic_task content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create courses_generic_task_solution content'
  $permissions['node:projects_organization:create courses_generic_task_solution content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create courses_group content'
  $permissions['node:projects_organization:create courses_group content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create courses_news content'
  $permissions['node:projects_organization:create courses_news content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create forum content'
  $permissions['node:projects_organization:create forum content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create h5p_content content'
  $permissions['node:projects_organization:create h5p_content content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create nm_stream content'
  $permissions['node:projects_organization:create nm_stream content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create projects_blog content'
  $permissions['node:projects_organization:create projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:create projects_documentation content'
  $permissions['node:projects_organization:create projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:create projects_objective content'
  $permissions['node:projects_organization:create projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:create projects_proposal content'
  $permissions['node:projects_organization:create projects_proposal content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:create webform content'
  $permissions['node:projects_organization:create webform content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:delete any biblio content'
  $permissions['node:projects_organization:delete any biblio content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any content_chapter content'
  $permissions['node:projects_organization:delete any content_chapter content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any content_multiple_choice content'
  $permissions['node:projects_organization:delete any content_multiple_choice content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any content_question_and_answer content'
  $permissions['node:projects_organization:delete any content_question_and_answer content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any courses_docs content'
  $permissions['node:projects_organization:delete any courses_docs content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any courses_generic_task content'
  $permissions['node:projects_organization:delete any courses_generic_task content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any courses_generic_task_solution content'
  $permissions['node:projects_organization:delete any courses_generic_task_solution content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any courses_group content'
  $permissions['node:projects_organization:delete any courses_group content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any courses_news content'
  $permissions['node:projects_organization:delete any courses_news content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any forum content'
  $permissions['node:projects_organization:delete any forum content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any h5p_content content'
  $permissions['node:projects_organization:delete any h5p_content content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any nm_stream content'
  $permissions['node:projects_organization:delete any nm_stream content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete any projects_blog content'
  $permissions['node:projects_organization:delete any projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:delete any projects_documentation content'
  $permissions['node:projects_organization:delete any projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:delete any projects_objective content'
  $permissions['node:projects_organization:delete any projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:delete any projects_proposal content'
  $permissions['node:projects_organization:delete any projects_proposal content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:delete any webform content'
  $permissions['node:projects_organization:delete any webform content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:delete own biblio content'
  $permissions['node:projects_organization:delete own biblio content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own content_chapter content'
  $permissions['node:projects_organization:delete own content_chapter content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own content_multiple_choice content'
  $permissions['node:projects_organization:delete own content_multiple_choice content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own content_question_and_answer content'
  $permissions['node:projects_organization:delete own content_question_and_answer content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own courses_docs content'
  $permissions['node:projects_organization:delete own courses_docs content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own courses_generic_task content'
  $permissions['node:projects_organization:delete own courses_generic_task content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own courses_generic_task_solution content'
  $permissions['node:projects_organization:delete own courses_generic_task_solution content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own courses_group content'
  $permissions['node:projects_organization:delete own courses_group content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own courses_news content'
  $permissions['node:projects_organization:delete own courses_news content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own forum content'
  $permissions['node:projects_organization:delete own forum content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own h5p_content content'
  $permissions['node:projects_organization:delete own h5p_content content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own nm_stream content'
  $permissions['node:projects_organization:delete own nm_stream content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own projects_blog content'
  $permissions['node:projects_organization:delete own projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:delete own projects_documentation content'
  $permissions['node:projects_organization:delete own projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:delete own projects_objective content'
  $permissions['node:projects_organization:delete own projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:delete own projects_proposal content'
  $permissions['node:projects_organization:delete own projects_proposal content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:delete own webform content'
  $permissions['node:projects_organization:delete own webform content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:edit any master profile'
  $permissions['node:projects_organization:edit any master profile'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:edit any student profile'
  $permissions['node:projects_organization:edit any student profile'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:manage members'
  $permissions['node:projects_organization:manage members'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:manage permissions'
  $permissions['node:projects_organization:manage permissions'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:manage roles'
  $permissions['node:projects_organization:manage roles'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:moderate'
  $permissions['node:projects_organization:moderate'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'forum administrator' => 'forum administrator',
    ),
  );

  // Exported og permission: 'node:projects_organization:subscribe'
  $permissions['node:projects_organization:subscribe'] = array(
    'roles' => array(
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:subscribe without approval'
  $permissions['node:projects_organization:subscribe without approval'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:unsubscribe'
  $permissions['node:projects_organization:unsubscribe'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any biblio content'
  $permissions['node:projects_organization:update any biblio content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any content_chapter content'
  $permissions['node:projects_organization:update any content_chapter content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any content_multiple_choice content'
  $permissions['node:projects_organization:update any content_multiple_choice content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any content_question_and_answer content'
  $permissions['node:projects_organization:update any content_question_and_answer content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any courses_docs content'
  $permissions['node:projects_organization:update any courses_docs content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any courses_generic_task content'
  $permissions['node:projects_organization:update any courses_generic_task content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any courses_generic_task_solution content'
  $permissions['node:projects_organization:update any courses_generic_task_solution content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any courses_group content'
  $permissions['node:projects_organization:update any courses_group content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any courses_news content'
  $permissions['node:projects_organization:update any courses_news content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any forum content'
  $permissions['node:projects_organization:update any forum content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any h5p_content content'
  $permissions['node:projects_organization:update any h5p_content content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any nm_stream content'
  $permissions['node:projects_organization:update any nm_stream content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any projects_blog content'
  $permissions['node:projects_organization:update any projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update any projects_documentation content'
  $permissions['node:projects_organization:update any projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update any projects_objective content'
  $permissions['node:projects_organization:update any projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update any projects_proposal content'
  $permissions['node:projects_organization:update any projects_proposal content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update any webform content'
  $permissions['node:projects_organization:update any webform content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update body field'
  $permissions['node:projects_organization:update body field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update comment_body field'
  $permissions['node:projects_organization:update comment_body field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_access_features field'
  $permissions['node:projects_organization:update field_access_features field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_answer field'
  $permissions['node:projects_organization:update field_answer field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_attachments field'
  $permissions['node:projects_organization:update field_attachments field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_blog_type field'
  $permissions['node:projects_organization:update field_blog_type field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_ca_cooperation_rules field'
  $permissions['node:projects_organization:update field_ca_cooperation_rules field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_ca_course_group_ref field'
  $permissions['node:projects_organization:update field_ca_course_group_ref field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_ca_expectation_academy field'
  $permissions['node:projects_organization:update field_ca_expectation_academy field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_ca_expectation_po field'
  $permissions['node:projects_organization:update field_ca_expectation_po field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_ca_instructors_role field'
  $permissions['node:projects_organization:update field_ca_instructors_role field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_ca_partners_role field'
  $permissions['node:projects_organization:update field_ca_partners_role field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_ca_proposal_ref field'
  $permissions['node:projects_organization:update field_ca_proposal_ref field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_ca_ref field'
  $permissions['node:projects_organization:update field_ca_ref field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_ca_result field'
  $permissions['node:projects_organization:update field_ca_result field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_ca_student_refs field'
  $permissions['node:projects_organization:update field_ca_student_refs field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_ca_students_role field'
  $permissions['node:projects_organization:update field_ca_students_role field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_ca_timespan field'
  $permissions['node:projects_organization:update field_ca_timespan field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_chapter_text field'
  $permissions['node:projects_organization:update field_chapter_text field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_collaborative_features field'
  $permissions['node:projects_organization:update field_collaborative_features field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_course_docs field'
  $permissions['node:projects_organization:update field_course_docs field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_course_group_proposal field'
  $permissions['node:projects_organization:update field_course_group_proposal field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_course_header field'
  $permissions['node:projects_organization:update field_course_header field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_course_picture field'
  $permissions['node:projects_organization:update field_course_picture field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_course_proposals field'
  $permissions['node:projects_organization:update field_course_proposals field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_courses_ref field'
  $permissions['node:projects_organization:update field_courses_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_domain_demo_ref field'
  $permissions['node:projects_organization:update field_domain_demo_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_domain_description field'
  $permissions['node:projects_organization:update field_domain_description field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_domain_picture field'
  $permissions['node:projects_organization:update field_domain_picture field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_domain_ref field'
  $permissions['node:projects_organization:update field_domain_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_domains_ref field'
  $permissions['node:projects_organization:update field_domains_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_field_courses_sponsors field'
  $permissions['node:projects_organization:update field_field_courses_sponsors field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_field_po_contact_person field'
  $permissions['node:projects_organization:update field_field_po_contact_person field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_file_image_alt_text field'
  $permissions['node:projects_organization:update field_file_image_alt_text field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_file_image_title_text field'
  $permissions['node:projects_organization:update field_file_image_title_text field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_generic_solution_entry field'
  $permissions['node:projects_organization:update field_generic_solution_entry field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_generic_task field'
  $permissions['node:projects_organization:update field_generic_task field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_generic_task_assessment field'
  $permissions['node:projects_organization:update field_generic_task_assessment field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_generic_task_entry field'
  $permissions['node:projects_organization:update field_generic_task_entry field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_long_description field'
  $permissions['node:projects_organization:update field_long_description field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_mc_solution field'
  $permissions['node:projects_organization:update field_mc_solution field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_mc_task field'
  $permissions['node:projects_organization:update field_mc_task field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_nm_attachments field'
  $permissions['node:projects_organization:update field_nm_attachments field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_nm_privacy field'
  $permissions['node:projects_organization:update field_nm_privacy field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_objective_matching field'
  $permissions['node:projects_organization:update field_objective_matching field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_objective_motivation field'
  $permissions['node:projects_organization:update field_objective_motivation field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_objective_task field'
  $permissions['node:projects_organization:update field_objective_task field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_operational_area field'
  $permissions['node:projects_organization:update field_operational_area field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_partner_organization_ref field'
  $permissions['node:projects_organization:update field_partner_organization_ref field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_po_contact field'
  $permissions['node:projects_organization:update field_po_contact field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_po_header field'
  $permissions['node:projects_organization:update field_po_header field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_po_logo field'
  $permissions['node:projects_organization:update field_po_logo field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_po_short_description field'
  $permissions['node:projects_organization:update field_po_short_description field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_projects_blog_attachments field'
  $permissions['node:projects_organization:update field_projects_blog_attachments field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_proposal_contact field'
  $permissions['node:projects_organization:update field_proposal_contact field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_proposal_expectation field'
  $permissions['node:projects_organization:update field_proposal_expectation field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_proposal_partners_role field'
  $permissions['node:projects_organization:update field_proposal_partners_role field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_proposal_result field'
  $permissions['node:projects_organization:update field_proposal_result field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_proposal_status field'
  $permissions['node:projects_organization:update field_proposal_status field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_proposal_students_role field'
  $permissions['node:projects_organization:update field_proposal_students_role field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_proposal_task_area field'
  $permissions['node:projects_organization:update field_proposal_task_area field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_proposal_timespan field'
  $permissions['node:projects_organization:update field_proposal_timespan field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_qaa_answer field'
  $permissions['node:projects_organization:update field_qaa_answer field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_qaa_question field'
  $permissions['node:projects_organization:update field_qaa_question field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_seal field'
  $permissions['node:projects_organization:update field_seal field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_semester field'
  $permissions['node:projects_organization:update field_semester field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_short_description field'
  $permissions['node:projects_organization:update field_short_description field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_space_header field'
  $permissions['node:projects_organization:update field_space_header field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_space_home field'
  $permissions['node:projects_organization:update field_space_home field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_subtitle field'
  $permissions['node:projects_organization:update field_subtitle field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_tableofcontents field'
  $permissions['node:projects_organization:update field_tableofcontents field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_task_area field'
  $permissions['node:projects_organization:update field_task_area field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update field_task_handling_period field'
  $permissions['node:projects_organization:update field_task_handling_period field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_task_type field'
  $permissions['node:projects_organization:update field_task_type field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_time_span field'
  $permissions['node:projects_organization:update field_time_span field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_vhb_lvnr field'
  $permissions['node:projects_organization:update field_vhb_lvnr field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update field_workload field'
  $permissions['node:projects_organization:update field_workload field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update group'
  $permissions['node:projects_organization:update group'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update group_content_access field'
  $permissions['node:projects_organization:update group_content_access field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update group_group field'
  $permissions['node:projects_organization:update group_group field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update og_group_ref field'
  $permissions['node:projects_organization:update og_group_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update og_user_node field'
  $permissions['node:projects_organization:update og_user_node field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own biblio content'
  $permissions['node:projects_organization:update own biblio content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own content_chapter content'
  $permissions['node:projects_organization:update own content_chapter content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own content_multiple_choice content'
  $permissions['node:projects_organization:update own content_multiple_choice content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own content_question_and_answer content'
  $permissions['node:projects_organization:update own content_question_and_answer content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own courses_docs content'
  $permissions['node:projects_organization:update own courses_docs content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own courses_generic_task content'
  $permissions['node:projects_organization:update own courses_generic_task content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own courses_generic_task_solution content'
  $permissions['node:projects_organization:update own courses_generic_task_solution content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own courses_group content'
  $permissions['node:projects_organization:update own courses_group content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own courses_news content'
  $permissions['node:projects_organization:update own courses_news content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own forum content'
  $permissions['node:projects_organization:update own forum content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own h5p_content content'
  $permissions['node:projects_organization:update own h5p_content content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own nm_stream content'
  $permissions['node:projects_organization:update own nm_stream content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own projects_blog content'
  $permissions['node:projects_organization:update own projects_blog content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update own projects_documentation content'
  $permissions['node:projects_organization:update own projects_documentation content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update own projects_objective content'
  $permissions['node:projects_organization:update own projects_objective content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update own projects_proposal content'
  $permissions['node:projects_organization:update own projects_proposal content'] = array(
    'roles' => array(
      'member' => 'member',
    ),
  );

  // Exported og permission: 'node:projects_organization:update own webform content'
  $permissions['node:projects_organization:update own webform content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:update taxonomy_forums field'
  $permissions['node:projects_organization:update taxonomy_forums field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view any master profile'
  $permissions['node:projects_organization:view any master profile'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view any student profile'
  $permissions['node:projects_organization:view any student profile'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view body field'
  $permissions['node:projects_organization:view body field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view comment_body field'
  $permissions['node:projects_organization:view comment_body field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_access_features field'
  $permissions['node:projects_organization:view field_access_features field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_answer field'
  $permissions['node:projects_organization:view field_answer field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_attachments field'
  $permissions['node:projects_organization:view field_attachments field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_blog_type field'
  $permissions['node:projects_organization:view field_blog_type field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_ca_cooperation_rules field'
  $permissions['node:projects_organization:view field_ca_cooperation_rules field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_ca_course_group_ref field'
  $permissions['node:projects_organization:view field_ca_course_group_ref field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_ca_expectation_academy field'
  $permissions['node:projects_organization:view field_ca_expectation_academy field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_ca_expectation_po field'
  $permissions['node:projects_organization:view field_ca_expectation_po field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_ca_instructors_role field'
  $permissions['node:projects_organization:view field_ca_instructors_role field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_ca_partners_role field'
  $permissions['node:projects_organization:view field_ca_partners_role field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_ca_proposal_ref field'
  $permissions['node:projects_organization:view field_ca_proposal_ref field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_ca_ref field'
  $permissions['node:projects_organization:view field_ca_ref field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_ca_result field'
  $permissions['node:projects_organization:view field_ca_result field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_ca_student_refs field'
  $permissions['node:projects_organization:view field_ca_student_refs field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_ca_students_role field'
  $permissions['node:projects_organization:view field_ca_students_role field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_ca_timespan field'
  $permissions['node:projects_organization:view field_ca_timespan field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_chapter_text field'
  $permissions['node:projects_organization:view field_chapter_text field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_collaborative_features field'
  $permissions['node:projects_organization:view field_collaborative_features field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_course_docs field'
  $permissions['node:projects_organization:view field_course_docs field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_course_group_proposal field'
  $permissions['node:projects_organization:view field_course_group_proposal field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_course_header field'
  $permissions['node:projects_organization:view field_course_header field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_course_picture field'
  $permissions['node:projects_organization:view field_course_picture field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_course_proposals field'
  $permissions['node:projects_organization:view field_course_proposals field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_courses_ref field'
  $permissions['node:projects_organization:view field_courses_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_domain_demo_ref field'
  $permissions['node:projects_organization:view field_domain_demo_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_domain_description field'
  $permissions['node:projects_organization:view field_domain_description field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_domain_picture field'
  $permissions['node:projects_organization:view field_domain_picture field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_domain_ref field'
  $permissions['node:projects_organization:view field_domain_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_domains_ref field'
  $permissions['node:projects_organization:view field_domains_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_field_courses_sponsors field'
  $permissions['node:projects_organization:view field_field_courses_sponsors field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_field_po_contact_person field'
  $permissions['node:projects_organization:view field_field_po_contact_person field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_file_image_alt_text field'
  $permissions['node:projects_organization:view field_file_image_alt_text field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_file_image_title_text field'
  $permissions['node:projects_organization:view field_file_image_title_text field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_generic_solution_entry field'
  $permissions['node:projects_organization:view field_generic_solution_entry field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_generic_task field'
  $permissions['node:projects_organization:view field_generic_task field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_generic_task_assessment field'
  $permissions['node:projects_organization:view field_generic_task_assessment field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_generic_task_entry field'
  $permissions['node:projects_organization:view field_generic_task_entry field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_long_description field'
  $permissions['node:projects_organization:view field_long_description field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_mc_solution field'
  $permissions['node:projects_organization:view field_mc_solution field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_mc_task field'
  $permissions['node:projects_organization:view field_mc_task field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_nm_attachments field'
  $permissions['node:projects_organization:view field_nm_attachments field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_nm_privacy field'
  $permissions['node:projects_organization:view field_nm_privacy field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_objective_matching field'
  $permissions['node:projects_organization:view field_objective_matching field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_objective_motivation field'
  $permissions['node:projects_organization:view field_objective_motivation field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_objective_task field'
  $permissions['node:projects_organization:view field_objective_task field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_operational_area field'
  $permissions['node:projects_organization:view field_operational_area field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_partner_organization_ref field'
  $permissions['node:projects_organization:view field_partner_organization_ref field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_po_contact field'
  $permissions['node:projects_organization:view field_po_contact field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'forum administrator' => 'forum administrator',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_po_header field'
  $permissions['node:projects_organization:view field_po_header field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'forum administrator' => 'forum administrator',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_po_logo field'
  $permissions['node:projects_organization:view field_po_logo field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'forum administrator' => 'forum administrator',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_po_short_description field'
  $permissions['node:projects_organization:view field_po_short_description field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'forum administrator' => 'forum administrator',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_projects_blog_attachments field'
  $permissions['node:projects_organization:view field_projects_blog_attachments field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_proposal_contact field'
  $permissions['node:projects_organization:view field_proposal_contact field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_proposal_expectation field'
  $permissions['node:projects_organization:view field_proposal_expectation field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_proposal_partners_role field'
  $permissions['node:projects_organization:view field_proposal_partners_role field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_proposal_result field'
  $permissions['node:projects_organization:view field_proposal_result field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_proposal_status field'
  $permissions['node:projects_organization:view field_proposal_status field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_proposal_students_role field'
  $permissions['node:projects_organization:view field_proposal_students_role field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_proposal_task_area field'
  $permissions['node:projects_organization:view field_proposal_task_area field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_proposal_timespan field'
  $permissions['node:projects_organization:view field_proposal_timespan field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_qaa_answer field'
  $permissions['node:projects_organization:view field_qaa_answer field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_qaa_question field'
  $permissions['node:projects_organization:view field_qaa_question field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_seal field'
  $permissions['node:projects_organization:view field_seal field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_semester field'
  $permissions['node:projects_organization:view field_semester field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_short_description field'
  $permissions['node:projects_organization:view field_short_description field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_space_header field'
  $permissions['node:projects_organization:view field_space_header field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_space_home field'
  $permissions['node:projects_organization:view field_space_home field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_subtitle field'
  $permissions['node:projects_organization:view field_subtitle field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_tableofcontents field'
  $permissions['node:projects_organization:view field_tableofcontents field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_task_area field'
  $permissions['node:projects_organization:view field_task_area field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:projects_organization:view field_task_handling_period field'
  $permissions['node:projects_organization:view field_task_handling_period field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_task_type field'
  $permissions['node:projects_organization:view field_task_type field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_time_span field'
  $permissions['node:projects_organization:view field_time_span field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_vhb_lvnr field'
  $permissions['node:projects_organization:view field_vhb_lvnr field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view field_workload field'
  $permissions['node:projects_organization:view field_workload field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view group_content_access field'
  $permissions['node:projects_organization:view group_content_access field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view group_group field'
  $permissions['node:projects_organization:view group_group field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view og_group_ref field'
  $permissions['node:projects_organization:view og_group_ref field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view og_user_node field'
  $permissions['node:projects_organization:view og_user_node field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:projects_organization:view taxonomy_forums field'
  $permissions['node:projects_organization:view taxonomy_forums field'] = array(
    'roles' => array(
      'administrator member' => 'administrator member',
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  return $permissions;
}
